<script lang="ts" setup>
import { useAppStore } from '@/stores/appSetting'

const AppSetting = useAppStore()

const themeColorGroup = [
  {
    span: 12,
    themeName: 'Element Plus (Light)',
    themeColorData: [
      // { label: '--el-color-white', data: '#ffffff' },
      // { label: '--el-color-black', data: '#000000' },
      { label: '--el-color-primary', data: '#409eff' },
      { label: '--el-color-primary-light-3', data: '#79bbff' },
      { label: '--el-color-primary-light-5', data: '#a0cfff' },
      { label: '--el-color-primary-light-7', data: '#c6e2ff' },
      { label: '--el-color-primary-light-8', data: '#d9ecff' },
      { label: '--el-color-primary-light-9', data: '#ecf5ff' },
      { label: '--el-color-primary-dark-2', data: '#337ecc' },
      { label: '--el-color-success', data: '#67c23a' },
      { label: '--el-color-success-light-3', data: '#95d475' },
      { label: '--el-color-success-light-5', data: '#b3e19d' },
      { label: '--el-color-success-light-7', data: '#d1edc4' },
      { label: '--el-color-success-light-8', data: '#e1f3d8' },
      { label: '--el-color-success-light-9', data: '#f0f9eb' },
      { label: '--el-color-success-dark-2', data: '#529b2e' },
      { label: '--el-color-warning', data: '#e6a23c' },
      { label: '--el-color-warning-light-3', data: '#eebe77' },
      { label: '--el-color-warning-light-5', data: '#f3d19e' },
      { label: '--el-color-warning-light-7', data: '#f8e3c5' },
      { label: '--el-color-warning-light-8', data: '#faecd8' },
      { label: '--el-color-warning-light-9', data: '#fdf6ec' },
      { label: '--el-color-warning-dark-2', data: '#b88230' },
      { label: '--el-color-danger', data: '#f56c6c' },
      { label: '--el-color-danger-light-3', data: '#f89898' },
      { label: '--el-color-danger-light-5', data: '#fab6b6' },
      { label: '--el-color-danger-light-7', data: '#fcd3d3' },
      { label: '--el-color-danger-light-8', data: '#fde2e2' },
      { label: '--el-color-danger-light-9', data: '#fef0f0' },
      { label: '--el-color-danger-dark-2', data: '#c45656' },
      { label: '--el-color-error', data: '#f56c6c' },
      { label: '--el-color-error-light-3', data: '#f89898' },
      { label: '--el-color-error-light-5', data: '#fab6b6' },
      { label: '--el-color-error-light-7', data: '#fcd3d3' },
      { label: '--el-color-error-light-8', data: '#fde2e2' },
      { label: '--el-color-error-light-9', data: '#fef0f0' },
      { label: '--el-color-error-dark-2', data: '#c45656' },
      { label: '--el-color-info', data: '#909399' },
      { label: '--el-color-info-light-3', data: '#b1b3b8' },
      { label: '--el-color-info-light-5', data: '#c8c9cc' },
      { label: '--el-color-info-light-7', data: '#dedfe0' },
      { label: '--el-color-info-light-8', data: '#e9e9eb' },
      { label: '--el-color-info-light-9', data: '#f4f4f5' },
      { label: '--el-color-info-dark-2', data: '#73767a' },
      { label: '--el-bg-color', data: '#ffffff' },
      { label: '--el-bg-color-page', data: '#f2f3f5' },
      { label: '--el-bg-color-overlay', data: '#ffffff' },
      { label: '--el-text-color-primary', data: '#303133' },
      { label: '--el-text-color-regular', data: '#606266' },
      { label: '--el-text-color-secondary', data: '#909399' },
      { label: '--el-text-color-placeholder', data: '#a8abb2' },
      { label: '--el-text-color-disabled', data: '#c0c4cc' },
      { label: '--el-border-color', data: '#dcdfe6' },
      { label: '--el-border-color-light', data: '#e4e7ed' },
      { label: '--el-border-color-lighter', data: '#ebeef5' },
      { label: '--el-border-color-extra-light', data: '#f2f6fc' },
      { label: '--el-border-color-dark', data: '#d4d7de' },
      { label: '--el-border-color-darker', data: '#cdd0d6' },
      { label: '--el-fill-color', data: '#f0f2f5' },
      { label: '--el-fill-color-light', data: '#f5f7fa' },
      { label: '--el-fill-color-lighter', data: '#fafafa' },
      { label: '--el-fill-color-extra-light', data: '#fafcff' },
      { label: '--el-fill-color-dark', data: '#ebedf0' },
      { label: '--el-fill-color-darker', data: '#e6e8eb' },
      { label: '--el-fill-color-blank', data: '#ffffff' },
      { label: '--el-mask-color', data: 'rgba(255, 255, 255, 0.9)' },
      { label: '--el-mask-color-extra-light', data: 'rgba(255, 255, 255, 0.3)' },
      {
        label: '--el-box-shadow',
        data: '0px 12px 32px 4px rgba(0, 0, 0, 0.04),	0px 8px 20px rgba(0, 0, 0, 0.08)',
      },
      { label: '--el-box-shadow-light', data: '0px 0px 12px rgba(0, 0, 0, 0.12)' },
      { label: '--el-box-shadow-lighter', data: '0px 0px 6px rgba(0, 0, 0, 0.12)' },
      {
        label: '--el-box-shadow-dark',
        data: '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12), 0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
      },
      { label: '--el-overlay-color', data: 'rgba(0, 0, 0, 0.8)' },
      { label: '--el-overlay-color-light', data: 'rgba(0, 0, 0, 0.7)' },
      { label: '--el-overlay-color-lighter', data: 'rgba(0, 0, 0, 0.5)' },      
      { label: '--el-color-primary-rgb', data: '64, 158, 255' },
      { label: '--el-color-success-rgb', data: '103, 194, 58' },
      { label: '--el-color-warning-rgb', data: '230, 162, 60' },
      { label: '--el-color-danger-rgb', data: '245, 108, 108' },
      { label: '--el-color-error-rgb', data: '245, 108, 108' },
      { label: '--el-color-info-rgb', data: '144, 147, 153' },
      { label: '--el-font-size-extra-large', data: '20px' },
      { label: '--el-font-size-large', data: '18px' },
      { label: '--el-font-size-medium', data: '16px' },
      { label: '--el-font-size-base', data: '14px' },
      { label: '--el-font-size-small', data: '13px' },
      { label: '--el-font-size-extra-small', data: '12px' },
      { label: '--el-font-family', data: 'notosans, Arial, sans-serif' },
      { label: '--el-font-weight-primary', data: '500' },
      { label: '--el-font-line-height-primary', data: '24px' },
      { label: '--el-index-normal', data: '1' },
      { label: '--el-index-top', data: '1000' },
      { label: '--el-index-popper', data: '2000' },
      { label: '--el-border-radius-base', data: '4px' },
      { label: '--el-border-radius-small', data: '2px' },
      { label: '--el-border-radius-round', data: '20px' },
      { label: '--el-border-radius-circle', data: '100%' },
      { label: '--el-component-size-large', data: '40px' },
      { label: '--el-component-size', data: '32px' },
      { label: '--el-component-size-small', data: '24px' },
      { label: '--el-popup-modal-opacity', data: '0.5' },
      { label: '--el-loading-spinner-size', data: '42px' },
      { label: '--el-loading-fullscreen-spinner-size', data: '50px' },
      { label: '--el-menu-item-height', data: '56px' },
      { label: '--el-menu-horizontal-height: 60px' },
      { label: '--el-menu-horizontal-sub-item-height', data: '36px' },
      { label: '--el-menu-base-level-padding', data: '20px' },
      { label: '--el-menu-level-padding', data: '20px' },
      { label: '--el-menu-icon-width', data: '24px' },
      { label: '--bg-color-rgb', data: '255, 255, 255' },
      { label: '--bg-color-soft', data: '#fafafa' },
      { label: '--bg-color-mute', data: '#f2f2f2' },
      { label: '--purple-color', data: '#6222c2' },
      { label: '--purple-color-light', data: '#9065db' },
      { label: '--header-height', data: '55px' },
      { label: '--nav-height', data: '55px' },
      { label: '--vp-screen-max-width', data: '1362px' },
      { label: '--vp-sidebar-width-mobile', data: '320px' },
      { label: '--vp-sidebar-width-small', data: '266px' },
      { label: '--sidebar-width-sm', data: '16rem' },
      { label: '--sidebar-width-xs', data: '20rem' },
      { label: '--content-min-width', data: '16rem' },
      { label: '--content-max-width', data: '48rem' },
      { label: '--nav-z-index', data: '12' },
      { label: '--sub-nav-z-index', data: '11' },
      { label: '--sidebar-z-index', data: '40' },
      { label: '--overlay-z-index', data: '30' },
      { label: '--code-line-height', data: '1.4' },
      { label: '--code-tooltip-color', data: '#0c61c9' },
    ],
  },
  {
    span: 12,
    themeName: 'Element Plus (Dark)',
    themeColorData: [
    { label: '--el-color-primary', data: '#5796ad' },
    { label: '--el-color-primary-light-3', data: '#436f7f' },
    { label: '--el-color-primary-light-5', data: '#365561' },
    { label: '--el-color-primary-light-7', data: '#283b42' },
    { label: '--el-color-primary-light-8', data: '#212e33' },
    { label: '--el-color-primary-light-9', data: '#1b2123' },
    { label: '--el-color-primary-dark-2', data: '#79abbd' },
    { label: '--el-color-success', data: '#67c23a' },
    { label: '--el-color-success-light-3', data: '#4e8e2f' },
    { label: '--el-color-success-light-5', data: '#3e6b27' },
    { label: '--el-color-success-light-7', data: '#2d481f' },
    { label: '--el-color-success-light-8', data: '#25371c' },
    { label: '--el-color-success-light-9', data: '#1c2518' },
    { label: '--el-color-success-dark-2', data: '#85ce61' },
    { label: '--el-color-warning', data: '#e6a23c' },
    { label: '--el-color-warning-light-3', data: '#a77730' },
    { label: '--el-color-warning-light-5', data: '#7d5b28' },
    { label: '--el-color-warning-light-7', data: '#533f20' },
    { label: '--el-color-warning-light-8', data: '#3e301c' },
    { label: '--el-color-warning-light-9', data: '#292218' },
    { label: '--el-color-warning-dark-2', data: '#ebb563' },
    { label: '--el-color-danger', data: '#f56c6c' },
    { label: '--el-color-danger-light-3', data: '#b25252' },
    { label: '--el-color-danger-light-5', data: '#854040' },
    { label: '--el-color-danger-light-7', data: '#582e2e' },
    { label: '--el-color-danger-light-8', data: '#412626' },
    { label: '--el-color-danger-light-9', data: '#2b1d1d' },
    { label: '--el-color-danger-dark-2', data: '#f78989' },
    { label: '--el-color-error', data: '#f56c6c' },
    { label: '--el-color-error-light-3', data: '#b25252' },
    { label: '--el-color-error-light-5', data: '#854040' },
    { label: '--el-color-error-light-7', data: '#582e2e' },
    { label: '--el-color-error-light-8', data: '#412626' },
    { label: '--el-color-error-light-9', data: '#2b1d1d' },
    { label: '--el-color-error-dark-2', data: '#f78989' },
    { label: '--el-color-info', data: '#909399' },
    { label: '--el-color-info-light-3', data: '#6b6d71' },
    { label: '--el-color-info-light-5', data: '#525457' },
    { label: '--el-color-info-light-7', data: '#393a3c' },
    { label: '--el-color-info-light-8', data: '#2d2d2f' },
    { label: '--el-color-info-light-9', data: '#202121' },
    { label: '--el-color-info-dark-2', data: '#a6a9ad' },
    { label: '--el-bg-color', data: '#141414' },
    { label: '--el-bg-color-page', data: '#0a0a0a' },
    { label: '--el-bg-color-overlay', data: '#1d1e1f' },
    { label: '--el-text-color-primary', data: '#E5EAF3' },
    { label: '--el-text-color-regular', data: '#CFD3DC' },
    { label: '--el-text-color-secondary', data: '#A3A6AD' },
    { label: '--el-text-color-placeholder', data: '#8D9095' },
    { label: '--el-text-color-disabled', data: '#6C6E72' },
    { label: '--el-border-color-darker', data: '#636466' },
    { label: '--el-border-color-dark', data: '#58585B' },
    { label: '--el-border-color', data: '#4C4D4F' },
    { label: '--el-border-color-light', data: '#414243' },
    { label: '--el-border-color-lighter', data: '#363637' },
    { label: '--el-border-color-extra-light', data: '#2B2B2C' },
    { label: '--el-fill-color-darker', data: '#424243' },
    { label: '--el-fill-color-dark', data: '#39393A' },
    { label: '--el-fill-color', data: '#303030' },
    { label: '--el-fill-color-light', data: '#262727' },
    { label: '--el-fill-color-lighter', data: '#1D1D1D' },
    { label: '--el-fill-color-extra-light', data: '#191919' },
    { label: '--el-fill-color-blank', data: 'transparent' },
    { label: '--el-mask-color', data: 'rgba(0, 0, 0, 0.8)' },
    { label: '--el-mask-color-extra-light', data: 'rgba(0, 0, 0, 0.3)' },
    { label: '--el-box-shadow', data: '0px 12px 32px 4px rgba(0, 0, 0, 0.36), 0px 8px 20px rgba(0, 0, 0, 0.72)' },
    { label: '--el-box-shadow-light', data: '0px 0px 12px rgba(0, 0, 0, 0.72)' },
    { label: '--el-box-shadow-lighter', data: '0px 0px 6px rgba(0, 0, 0, 0.72)' },
    { label: '--el-box-shadow-dark', data: '0px 16px 48px 16px rgba(0, 0, 0, 0.72), 0px 12px 32px #000000, 0px 8px 16px -8px #000000' },    
    ],
  },
  {
    span: 8,
    themeName: 'CALS(core)',
    themeColorData: [
    { label: '--color-primary-10', data: '#f5fafc' },
      { label: '--color-primary-20', data: '#f4f7f8' },
      { label: '--color-primary-30', data: '#f3f5f5' },
      { label: '--color-primary-40', data: '#e7f3f7' },
      { label: '--color-primary-50', data: '#dae6eb' },
      { label: '--color-primary-60', data: '#9fcad9' },
      { label: '--color-primary-70', data: '#5796ad' },
      { label: '--color-primary-80', data: '#3386a2' },
      { label: '--color-primary-90', data: '#055a78' },
      { label: '--color-primary-100', data: '#2f657d' },
      { label: '--color-icon-10', data: '#f3b45b' },
      { label: '--color-icon-20', data: '#0e8bff' },
      { label: '--color-icon-30', data: '#fe8057' },
      { label: '--color-icon-40', data: '#2aaeb1' },
      { label: '--color-icon-50', data: '#8c8c8c' },
      { label: '--color-icon-60', data: '#ffce00' },
      { label: '--color-gray-10', data: '#fff' },
      { label: '--color-gray-20', data: '#f6f6f6' },
      { label: '--color-gray-30', data: '#f1f1f1' },
      { label: '--color-gray-40', data: '#e8e8e8' },
      { label: '--color-gray-50', data: '#ddd' },
      { label: '--color-gray-60', data: '#c1c4cc' },
      { label: '--color-gray-70', data: '#909399' },
      { label: '--color-gray-80', data: '#606266' },
      { label: '--color-gray-90', data: '#222' },
      { label: '--color-gray-100', data: '#000' },
      { label: '--color-gray-110', data: '#f0f3f5' },
      { label: '--color-semantic-success', data: '#2fc898' },
      { label: '--color-semantic-success10', data: '#6cddba' },
      { label: '--color-semantic-success20', data: '#baf1e1' },
      { label: '--color-semantic-danger', data: '#f56c6c' },
      { label: '--color-semantic-danger10', data: '#feb5b6' },
      { label: '--color-semantic-danger20', data: '#ffe4e4' },
      { label: '--color-semantic-warning', data: '#e6a23c' },
      { label: '--color-semantic-warning10', data: '#f2c98b' },
      { label: '--color-semantic-warning20', data: '#fff3dd' },
      { label: '--color-semantic-required', data: '#f75456' },
      { label: '--color-semantic-currentday', data: '#e3165b' },
      { label: '--color-semantic-info', data: '#909399' },
      { label: '--color-semantic-info10', data: '#bcbec5' },
      { label: '--color-semantic-info20', data: '#f1f1fd' },
      { label: '--color-header-icon-default', data :' #3386a2' },
      { label: '--color-header-background-default', data :' #fff' },
      { label: '--color-header-dropdownmenu-item-background-hover', data: '#dae6eb' },
      { label: '--color-header-dropdownmenu-item-font-default', data: '#5796ad' },
      { label: '--color-header-dropdownmenu-item-font-hover', data: '#055a78' },
      { label: '--color-dropdown-background-default', data: '#fff' },
      { label: '--color-dropdown-boxshadow', data: '#0000001f' },
      { label: '--color-dropdownmenu-item-background-hover', data: '#f1f1f1' },
      { label: '--color-dropdownmenu-item-font-default', data: '#606266' },
      { label: '--color-dropdownmenu-item-font-hover', data: '#222' },
      { label: '--color-dropdownmenu-item-font-disabled', data: '#909399' },
      { label: '--color-avatar-name-font', data: '#606266' },
      { label: '--color-breadcrumb-icon-default', data: '#606266' },
      { label: '--color-breadcrumb-font-active', data: '#5796ad' },
      { label: '--color-breadcrumb-font-default', data: '#222' },
      { label: '--color-breadcrumb-font-hover', data: '#3386a2' },
      { label: '--color-tags-item-background-default', data: '#fff' },
      { label: '--color-tags-item-background-active', data: '#9fcad9' },
      { label: '--color-tags-item-font-active', data: '#2f657d' },
      { label: '--color-tags-item-font-default', data: '#c1c4cc' },
      { label: '--color-tags-item-border-active', data: '#9fcad9' },
      { label: '--color-tags-item-border-default', data: '#fff' },
      { label: '--color-tags-item-close-border-default', data: '#c1c4cc' },
      { label: '--color-tags-item-close-border-selected', data: '#fff' },
      { label: '--color-tags-item-close-background-default', data: '#fff' },
      { label: '--color-tags-item-close-background-selected', data: '#9fcad9' },
      { label: '--color-tags-contextmenu-border-color', data: '#ddd' },
      { label: '--color-tags-contextmenu-background-color-default', data: '#fff' },
      { label: '--color-tags-contextmenu-background-color-hover', data: '#e7f3f7' },
      { label: '--color-button-default-background-default', data: '#fff' },
      { label: '--color-button-default-background-disabled', data: '#fff' },
      { label: '--color-button-default-background-hover', data: '#e8e8e8' },
      { label: '--color-button-default-font-default', data: '#000' },
      { label: '--color-button-default-font-disabled', data: '#909399' },
      { label: '--color-button-default-font-hover', data: '#000' },
      { label: '--color-button-default-border-default', data: 'transparent' },
      { label: '--color-button-default-border-disabled', data: 'transparent' },
      { label: '--color-button-default-border-hover', data: 'transparent' },
      { label: '--color-button-lookup-default', data: '#055a78' },
      { label: '--color-confirm-border-default', data: '#e7f3f7' },
      { label: '--color-confirm-header-border', data: '#055a78' },
      { label: '--color-confirm-title', data: '#055a78' },
      { label: '--color-confirm-button-confirm-background-default', data: '#e7f3f7' },
      { label: '--color-confirm-button-confirm-border-default', data: '#dae6eb' },
      { label: '--color-confirm-button-confirm-font-default', data: '#2f657d' },
      { label: '--color-confirm-button-cancel-background-default', data: '#fff' },
      { label: '--color-confirm-button-cancel-border-default', data: '#ddd' },
      { label: '--color-confirm-button-cancel-font-default', data: '#909399' },
      { label: '--color-confirm-boxshadow', data: '#0000003d' },
      { label: '--color-form-button-font-default', data: '#055a78' },
      { label: '--color-form-button-font-disabled', data: '#909399' },
      { label: '--color-form-button-font-hover', data: '#055a78' },
      { label: '--color-form-button-border-default', data: '#e8e8e8' },
      { label: '--color-form-button-border-disabled', data: '#e8e8e8' },
      { label: '--color-form-button-border-hover', data: '#e8e8e8' },
      { label: '--color-form-button-background-default', data: '#fff' },
      { label: '--color-form-button-background-disabled', data: '#f1f1f1' },
      { label: '--color-form-button-background-hover', data: '#e8e8e8' },
      { label: '--color-input-background-default', data: '#fff' },
      { label: '--color-input-background-hover', data: '#fff' },
      { label: '--color-input-background-disabled', data: '#f1f1f1' },
      { label: '--color-input-border-default', data: '#e8e8e8' },
      { label: '--color-input-border-hover', data: '#9fcad9' },
      { label: '--color-input-border-disabled', data: '#e8e8e8' },
      { label: '--color-input-font-placeholder', data: '#c1c4cc' },
      { label: '--color-input-font-disabled', data: '#606266' },
      { label: '--color-input-font-hover', data: '#000' },
      { label: '--color-input-font-default', data: '#000' },
      { label: '--color-required-border', data: '#f75456' },
      { label: '--color-radio-border-checked', data: '#055a78' },
      { label: '--color-radio-border-default', data: '#c1c4cc' },
      { label: '--color-radio-background-checked', data: '#fff' },
      { label: '--color-radio-background-default', data: '#fff' },
      { label: '--color-radio-pseudo-background-checked', data: '#055a78' },
      { label: '--color-radio-pseudo-background-default', data: '#fff' },
      { label: '--color-checkbox-border-checked', data: '#055a78' },
      { label: '--color-checkbox-border-default', data: '#c1c4cc' },
      { label: '--color-checkbox-border-disabled', data: '#c1c4cc' },
      { label: '--color-checkbox-border-both', data: '#055a78' },
      { label: '--color-checkbox-background-checked', data: '#fff' },
      { label: '--color-checkbox-background-default', data: '#fff' },
      { label: '--color-checkbox-background-disabled', data: '#f1f1f1' },
      { label: '--color-checkbox-background-both', data: '#055a78' },
      { label: '--color-checkbox-pseudo-border-checked', data: '#055a78' },
      { label: '--color-checkbox-pseudo-border-default', data: '#fff' },
      { label: '--color-checkbox-pseudo-border-disabled', data: '#c1c4cc' },
      { label: '--color-checkbox-pseudo-border-both', data: '#fff' },
      { label: '--color-tab-border-default', data: '#9fcad9' },
      { label: '--color-tab-item-background-selected', data: '#9fcad9' },
      { label: '--color-tab-item-background-default', data: '#fff' },
      { label: '--color-tab-item-background-hover', data: '#fff' },
      { label: '--color-tab-item-background-extension-depth1', data: '#055a78' },
      { label: '--color-tab-item-background-extension-depth2', data: '#5796ad' },
      { label: '--color-tab-item-border-selected', data: '#9fcad9' },
      { label: '--color-tab-item-border-default', data: '#9fcad9' },
      { label: '--color-tab-item-border-hover', data: '#9fcad9' },
      { label: '--color-tab-item-border-extension-depth1', data: '#055a78' },
      { label: '--color-tab-item-border-extension-depth2', data: '#5796ad' },
      { label: '--color-tab-item-font-selected', data: '#055a78' },
      { label: '--color-tab-item-font-default', data: '#606266' },
      { label: '--color-tab-item-font-hover', data: '#3386a2' },
      { label: '--color-tab-item-font-extension-default', data: '#909399' },
      { label: '--color-tab-item-font-extension-selected', data: '#fff' },
      { label: '--color-comment-border-default', data: '#ddd' },
      { label: '--color-comment-more-button-default', data: '#000' },
      { label: '--color-comment-more-button-background-default', data: '#fff' },
      { label: '--color-comment-more-button-background-hover', data: '#f6f6f6' },
      { label: '--color-popup-background-default', data: '#fff' },
      { label: '--color-popup-header-background', data: '#f0f3f5' },
      { label: '--color-popup-close-button-background', data: 'transparent' },
      { label: '--color-popup-boxshadow', data: '#0000004a' },
      { label: '--color-timeline-item-tail', data: '#e8e8e8' },
      { label: '--color-timeline-item-backgrond-default', data: '#fff' },
      { label: '--color-timeline-item-title-color-default', data: '#909399' },
      { label: '--color-timeline-item-content-color-default', data: '#606266' },
      { label: '--color-step-success', data: '#5796ad' },
      { label: '--color-step-process', data: '#222' },
      { label: '--color-step-wait', data: '#909399' },
      { label: '--color-theme-primary', data: '#5796ad' },
      { label: '--color-select-dropdown-background-default', data: '#fff' },
      { label: '--color-select-dropdown-background-hover', data: '#f5fafc' },
      { label: '--color-select-dropdown-background-selected', data: '#e7f3f7' },
      { label: '--color-select-dropdown-font-default', data: '#909399' },
      { label: '--color-select-dropdown-font-selected', data: '#055a78' },
      { label: '--color-select-dropdown-font-hover', data: '#606266' },
      { label: '--color-select-dropdown-font-disabled', data: '#909399' },
      { label: '--color-select-dropdown-boxshadow', data: '#0000001f' },
      { label: '--color-anchor-font-default', data: '#007dbc' },
      { label: '--color-anchor-font-hover', data: '#4bafc8b3' },
      { label: '--color-anchor-font-visited', data: '#005b86' },
      { label: '--color-list-cell-border-default', data: '#e8e8e8' },
      { label: '--color-list-head-leaf-border-bottom', data: '#c1c4cc' },
      { label: '--color-list-head-cell-searched-font-default', data: '#5796ad' },
      { label: '--color-list-head-cell-sort-font-default', data: '#c1c4cc' },
      { label: '--color-list-head-cell-sort-font-selected', data: '#5796ad' },
      { label: '--color-list-head-cell-background-default', data: '#f5fafc' },
      { label: '--color-list-head-cell-font-default', data: '#000' },
      { label: '--color-list-body-cell-background-default', data: '#fff' },
      { label: '--color-list-body-cell-background-hover', data: '#f6f6f6' },
      { label: '--color-list-body-cell-background-selected', data: '#e7f3f7' },
      { label: '--color-list-body-cell-background-subtotal', data: '#ddd' },
      { label: '--color-list-body-cell-empty-font-default', data: '#f6f6f6' },
      { label: '--color-list-body-cell-required-font-default', data: '#f75456' },
      { label: '--color-list-body-cell-total-font-default', data: '#5796ad' },
      { label: '--color-list-body-cell-progress-border-default', data: '#c1c4cc' },
      { label: '--color-list-body-cell-progress-background-default', data: '#9fcad9' },
      { label: '--color-list-body-cell-rating-default', data: '#dae6eb' },
      { label: '--color-list-body-cell-rating-active', data: '#ffce00' },
      { label: '--color-list-body-cell-font-default', data: '#000' },
      { label: '--color-list-pager-selected', data: '#5796ad' },
      { label: '--color-list-pager-default', data: '#c1c4cc' },
      { label: '--color-list-loading-stroke', data: '#5796ad' },
      { label: '--color-list-footer-cell-background-default', data: '#f6f6f6' },
      { label: '--color-alert-info-border-default', data: '#bcbec5' },
      { label: '--color-alert-info-font-default', data: '#909399' },
      { label: '--color-alert-info-background-default', data: '#f1f1fd' },
      { label: '--color-alert-success-border-default', data: '#6cddba' },
      { label: '--color-alert-success-font-default', data: '#2fc898' },
      { label: '--color-alert-success-background-default', data: '#baf1e1' },
      { label: '--color-alert-warning-border-default', data: '#f2c98b' },
      { label: '--color-alert-warning-font-default', data: '#e6a23c' },
      { label: '--color-alert-warning-background-default', data: '#fff3dd' },
      { label: '--color-alert-danger-border-default', data: '#feb5b6' },
      { label: '--color-alert-danger-font-default', data: '#f56c6c' },
      { label: '--color-alert-danger-background-default', data: '#ffe4e4' },
      { label: '--color-alert-boxshadow', data: '#00000059' },
      { label: '--color-datepicker-highlight', data: '#2aaeb1' },
      { label: '--color-datepicker-boxshadow', data: '#0000001a' },
      { label: '--color-datepicker-event-default', data: '#2fc898' },
      { label: '--color-font-default', data: '#000' },
      { label: '--color-schedule-current-date', data: '#e3165b' },
      { label: '--color-schedule-background-default', data: '#fff' },
      { label: '--color-sidebar-background-default', data: '#f4f7f8' },
      { label: '--color-sidebar-menu-border-default', data: '#dae6eb' },
      { label: '--color-sidebar-collapse-title-font-default', data: '#fff' },
      { label: '--color-sidebar-collapse-title-background-default', data: '#3386a2' },
      { label: '--color-sidebar-collapse-menu-background-hover', data: '#f4f7f8' },
      { label: '--color-sidebar-collapse-menu-background-default', data: '#fff' },
      { label: '--color-sidebar-depth1-color-default', data: '#3386a2' },
      { label: '--color-sidebar-depth1-color-select', data: '#2f657d' },
      { label: '--color-sidebar-depth1-edge', data: 'transparent' },
      { label: '--color-sidebar-depth1-background-default', data: 'transparent' },
      { label: '--color-sidebar-depth2-color-default', data: '#3386a2' },
      { label: '--color-sidebar-depth2-color-select', data: '#2f657d' },
      { label: '--color-sidebar-depth2-edge', data: '#9fcad9' },
      { label: '--color-sidebar-depth2-background', data: 'efault: transparent' },
      { label: '--color-sidebar-depth3-color-default', data: '#3386a2' },
      { label: '--color-sidebar-depth3-color-select', data: '#2f657d' },
      { label: '--color-sidebar-depth3-edge', data: '#5796ad' },
      { label: '--color-sidebar-depth3-background', data: 'efault: transparent' },
      { label: '--color-sidebar-depth4-color-default', data: '#3386a2' },
      { label: '--color-sidebar-depth4-color-select', data: '#2f657d' },
      { label: '--color-sidebar-depth4-edge', data: '#3386a2' },
      { label: '--color-sidebar-depth4-background-default', data: 'transparent' },
      { label: '--color-sidebar-depth5-color-default', data: '#3386a2' },
      { label: '--color-sidebar-depth5-color-select', data: '#2f657d' },
      { label: '--color-sidebar-depth5-edge', data: '#055a78' }, 
      { label: '--color-sidebar-depth5-background-default', data: 'transparent' },
      { label: '--color-sidebar-item-boxshadow', data: '#0000001f' },
      { label: '--color-sidebar-boxshadow', data: '#0000001f' },
      { label: '--color-scrollbar-default', data: '#9093994d' },
      { label: '--color-scrollbar-hover', data: '#90939980' },
      { label: '--color-kanban-background', data: '#f6f6f6' },
      { label: '--color-kanban-header-background', data: '#5796ad' },
      { label: '--color-kanban-header-title', data: '#fff' },
      { label: '--color-kanban-header-count', data: '#f1f1f1' },
      { label: '--color-kanban-card-background', data: '#fff' },
      { label: '--color-kanban-card-title', data: '#000' },
      { label: '--color-kanban-card-content', data: '#606266' },
      { label: '--color-kanban-card-tags-background', data: '#dae6eb' },
      { label: '--color-kanban-card-tags-default', data: '#3386a2' },
      { label: '--color-kanban-card-boxshadow', data: '#00000029' },
      { label: '--color-right-panel-background', data: '#f6f6f6' },
      { label: '--color-right-panel-boxshadow', data: '#0000001f' },
      { label: '--color-bottom-panel-background', data: '#f6f6f6' },
      { label: '--color-bottom-panel-border', data: '#c1c4cc' },
      { label: '--color-bottom-panel-boxshadow', data: '#0000001f' },
      { label: '--color-label-edge-background', data: '#909399' },
      { label: '--color-fileupload-desc-font', data: '#909399' },
      { label: '--color-fileupload-border', data: '#e8e8e8' },
      { label: '--color-fileupload-info-font', data: '#606266' },
      { label: '--color-fileupload-info-file-open-font', data: '#5796ad' },
      { label: '--color-fileupload-info-background', data: '#fff' },
      { label: '--color-fileupload-info-progress-background', data: '#c1c4cc' },
      { label: '--color-image-view-background', data: '#f4f7f8' },
      { label: '--color-box-label', data: '#c1c4cc' },
      { label: '--color-box-icon-background', data: '#f4f7f8' },
      { label: '--color-tree-button-default', data: '#055a78' },
      { label: '--color-component-background', data: '#fff' },
      { label: '--color-component-title-border', data: '#9fcad9' },
      { label: '--color-component-title-arrow-color', data: '#606266' },
      { label: '--color-app-wrapper-background', data: '#f3f5f5' },
      { label: '--color-inlineedittoolbar-icon-background', data: '#fff' },
      { label: '--color-inlineedittoolbar-icon-new', data: '#f3b45b' },
      { label: '--color-inlineedittoolbar-icon-edit', data: '#0e8bff' },
      { label: '--color-inlineedittoolbar-icon-delete', data: '#fe8057' },
      { label: '--color-inlineedittoolbar-icon-save', data: '#2aaeb1' },
      { label: '--color-inlineedittoolbar-icon-cancel', data: '#8c8c8c' },
      { label: '--color-overlay-loading-font', data: '#fff' },
      { label: '--color-overlay-loading-boxshadow', data: '#0000004d' },
      { label: '--color-vfm-background', data: '#00000033' },
      { label: '--color-sitemap-menu-search-border-focus', data: '#c1c4cc' },
      { label: '--color-sitemap-menu-search-font', data: '#f75456' },
      { label: '--color-sitemap-menu-match-font', data: '#fff' },
      { label: '--color-sitemap-menu-font', data: '#222' },
      { label: '--color-secondary-10', data: '#007dbc' },
      { label: '--color-secondary-20', data: '#4bafc8b3' },
      { label: '--color-secondary-30', data: '#005b86' },
      { label: '--color-secondary-40', data: '#f9fbf5' },
      { label: '--color-secondary-50', data: '#fff' },
      { label: '--color-secondary-60', data: '#fff' },
      { label: '--color-notification-icon-count-color', data: '#fff' },
      { label: '--color-notification-icon-count-background-color', data: '#e3165b' },
      { label: '--color-notification-item-urgent-background-color', data: '#ffe4e4' },
      { label: '--color-notification-item-urgent-border-color', data: '#feb5b6' },
      { label: '--color-notification-item-icon-check-receipt-color', data: '#3386a2' },
      { label: '--color-notification-popup-item-urgent-background-color', data: '#ffe4e4' },
      { label: '--color-focus-border', data: '#5796ad' },
      { label: '--fontfamily-default', data: 'notosans' },
      { label: '--fontweight-100', data: 100 },
      { label: '--fontweight-300', data: 300 },
      { label: '--fontweight-400', data: 400 },
      { label: '--fontweight-500', data: 500 },
      { label: '--fontweight-700', data: 700 },
      { label: '--fontweight-900', data: 900 },
      { label: '--fontweight-default:',  data: 400 },
      { label: '--fontweight-tab-item', data: 400 },
      { label: '--fontweight-popup-title', data: 700 },
      { label: '--fontweight-confirm-button', data: 700 },
      { label: '--fontweight-box-label', data: 500 },
      { label: '--fontweight-box-data', data: 700 },
      { label: '--fontweight-button-default', data: 500 },
      { label: '--fontweight-form-button', data: 500 },
      { label: '--fontweight-list-cell', data: 300 },
      { label: '--fontweight-list-header', data: 500 },
      { label: '--fontweight-list-pager-selected', data: 500 },
      { label: '--fontweight-list-body-row-selected', data: 300 },
      { label: '--fontweight-input', data: 400 },
      { label: '--fontweight-breadcrumb-default', data: 400 },
      { label: '--fontweight-breadcrumb-active', data: 400 },
      { label: '--fontweight-avatar-name', data: 500 },
      { label: '--fontweight-sidebar-default', data: 400 },
      { label: '--fontweight-sidebar-hover', data: 500 },
      { label: '--fontweight-sidebar-selected', data: 500 },
      { label: '--fontweight-tags-item', data: 400 },
      { label: '--fontweight-component-title-arrow', data: 700 },
      { label: '--fontweight-kanban-header-title', data: 500 },
      { label: '--fontweight-kanban-card-title', data: 500 },
      { label: '--fontweight-fileupload-desc', data: 400 },
      { label: '--fontweight-comment-more-button', data: 500 },
      { label: '--borderradius-default', data: '4px' },
      { label: '--fontsize-default', data: '14px' },
      { label: '--fontsize-xs', data: .75 },
      { label: '--fontsize-2xs', data: .563 },
      { label: '--fontsize-s', data: .875 },
      { label: '--fontsize-m', data: 1 },
      { label: '--fontsize-l', data: 1.15 },
      { label: '--fontsize-xl', data: 1.25 },
      { label: '--fontsize-2xl', data: 1.5 },
      { label: '--fontsize-3xl', data: 3.5 },
      { label: '--fontsize-h1', data: '78.75px' },
      { label: '--fontsize-h2', data: '52.5px' },
      { label: '--fontsize-h3', data: '42px' },
      { label: '--fontsize-h4', data: '29.75px' },
      { label: '--fontsize-h5', data: '21px' },
      { label: '--fontsize-h6', data: '12.25px' },
      { label: '--fontsize-sidebar-default', data: '12.25px' },
      { label: '--fontsize-sidebar-selected', data: '16.099999999999998px' },
      { label: '--fontsize-sidebar-collapse-icon', data: '16.099999999999998px' },
      { label: '--fontsize-sidebar-hover', data: '12.25px' },
      { label: '--fontsize-base', data: '12.25px' },
      { label: '--fontsize-component-title-arrow', data: '17.5px' },
      { label: '--fontsize-comment-more-button', data: '14px' },
      { label: '--fontsize-kanban-header-title', data: '16.099999999999998px' },
      { label: '--fontsize-kanban-header-count', data: '12.25px' },
      { label: '--fontsize-kanban-card-title', data: '16.099999999999998px' },
      { label: '--fontsize-kanban-card-content', data: '14px' },
      { label: '--fontsize-kanban-card-tags', data: '12.25px' },
      { label: '--fontsize-list-cell-default', data: '12.25px' },
      { label: '--fontsize-list-cell-direct-edit', data: '17.5px' },
      { label: '--fontsize-list-cell-rating', data: '17.5px' },
      { label: '--fontsize-tab-item', data: '14px' },
      { label: '--fontsize-tree-node', data: '14px' },
      { label: '--fontsize-tree-button', data: '16.099999999999998px' },
      { label: '--fontsize-box-label', data: '16.099999999999998px' },
      { label: '--fontsize-box-data-suffix', data: '21px' },
      { label: '--fontsize-box-data-default', data: '49px' },
      { label: '--fontsize-fileupload-detail-info', data: '12.25px' },
      { label: '--fontsize-fileupload-desc', data: '10.5px' },
      { label: '--fontsize-input', data: '12.25px' },
      { label: '--fontsize-label', data: '12.25px' },
      { label: '--fontsize-inlineedittoolbar-icon', data: '14px' },
      { label: '--fontsize-breadcrumb-default', data: '16.099999999999998px' },
      { label: '--fontsize-breadcrumb-active', data: '16.099999999999998px' },
      { label: '--fontsize-dropdownmenu-item', data: '12.25px' },
      { label: '--fontsize-header-icon', data: '21px' },
      { label: '--fontsize-header-dropdownmenu-item', data: '14px' },
      { label: '--fontsize-avatar-name', data: '16.099999999999998px' },
      { label: '--fontsize-tags-item', data: '14px' },
      { label: '--fontsize-popup-title', data: '16.099999999999998px' },
      { label: '--fontsize-popup-close-button', data: '21px' },
      { label: '--fontsize-confirm-content', data: '16.099999999999998px' },
      { label: '--fontsize-confirm-button', data: '16.099999999999998px' },
      { label: '--fontsize-button-default', data: '12.25px' },
      { label: '--fontsize-form-button', data: '12.25px' },
      { label: '--fontsize-step-default', data: '16.099999999999998px' },
      { label: '--spacing-gap-s', data: '5px' },
      { label: '--spacing-gap-m', data: '7.5px' },
      { label: '--spacing-gap-default', data: '7.5px' },
      { label: '--spacing-gap-l', data: '10px' },
      { label: '--spacing-gap-xl', data: '15px' },
      { label: '--spacing-gap-2xl', data: '20px' },
      { label: '--spacing-gap-3xl', data: '30px' },
      { label: '--spacing-gap-xs', data: '4.5px' },
      { label: '--spacing-kanban-padding-top', data: '10px' },
      { label: '--spacing-kanban-card-tags-x', data: '6px' },
      { label: '--spacing-kanban-card-tags-y', data: '2px' },
      { label: '--spacing-kanban-card-tags-margin', data: '15px' },
      { label: '--spacing-kanban-card-padding', data: '10px' },
      { label: '--spacing-rightpanel-x', data: '20px' },
      { label: '--spacing-bottompanel-x', data: '20px' },
      { label: '--spacing-sidebar-sidemenu-level', data: '20px' },
      { label: '--spacing-list-cell-x', data: '7.5px' },
      { label: '--spacing-list-cell-y', data: '6.5px' },
      { label: '--spacing-tab-padding-y', data: '10px' },
      { label: '--spacing-tab-item-padding-x', data: '20px' },
      { label: '--spacing-tab-item-margin-left', data: '15px' },
      { label: '--spacing-layout-padding-x', data: '20px' },
      { label: '--spacing-component-padding-top', data: '5px' },
      { label: '--spacing-component-margin-bottom', data: '15px' },
      { label: '--spacing-input-padding-x', data: '7.5px' },
      { label: '--spacing-input-padding-y', data: '5px' },
      { label: '--spacing-textarea-x', data: '15px' },
      { label: '--spacing-textarea-y', data: '5px' },
      { label: '--spacing-tree-padding-top', data: '10px' },
      { label: '--spacing-header-item-margin-x', data: '20px' },
      { label: '--spacing-tags-padding-y', data: '10px' },
      { label: '--spacing-tags-item-margin-x', data: '15px' },
      { label: '--spacing-tags-item-y', data: '4px' },
      { label: '--spacing-tags-item-x', data: '10px' },
      { label: '--spacing-comment-item-margin-bottom', data: '10px' },
      { label: '--spacing-comment-more-button-padding-y', data: '10px' },
      { label: '--spacing-comment-padding', data: '15px' },
      { label: '--spacing-timeline-padding-top', data: '10px' },
      { label: '--spacing-timeline-item-title-margin-bottom', data: '15px' },
      { label: '--spacing-schedule-padding-top', data: '10px' },
      { label: '--spacing-form-padding-top', data: '10px' },
      { label: '--spacing-form-item-margin-bottom', data: '20px' },
      { label: '--spacing-form-item-label-margin-bottom', data: '2px' },
      { label: '--opacity-inlineedittoolbar-icon', data: '20%' },
      { label: '--opacity-overlay-loading', data: '30%' },
      { label: '--sizing-scrollbar', data: '6px' },
    ],
  },
  {
    span: 8,
    themeName: 'CALS(yellow)',
    themeColorData: [
      { label: '--color-primary-10', data: '#fffdf5' },
      { label: '--color-primary-20', data: '#fff8e0' },
      { label: '--color-primary-30', data: '#ffefb5' },
      { label: '--color-primary-40', data: '#fee500' },
      { label: '--color-primary-50', data: '#ffb800' },
      { label: '--color-primary-60', data: '#d98912' },
      { label: '--color-primary-70', data: '#8e5c12' },
      { label: '--color-primary-80', data: '#76400b' },
      { label: '--color-primary-90', data: '#5e4d3d' },
      { label: '--color-primary-100', data: '#3b3735' },
      { label: '--color-icon-10', data: '#00c2ff' },
      { label: '--color-icon-20', data: '#06f' },
      { label: '--color-icon-30', data: '#ff5c00' },
      { label: '--color-icon-40', data: '#0d6b49' },
      { label: '--color-icon-50', data: '#68686f' },
      { label: '--color-icon-60', data: '#ffce00' },
      { label: '--color-gray-10', data: '#fff' },
      { label: '--color-gray-20', data: '#f6f6f6' },
      { label: '--color-gray-30', data: '#f1f1f1' },
      { label: '--color-gray-40', data: '#e8e8e8' },
      { label: '--color-gray-50', data: '#ddd' },
      { label: '--color-gray-60', data: '#c1c4cc' },
      { label: '--color-gray-70', data: '#909399' },
      { label: '--color-gray-80', data: '#606266' },
      { label: '--color-gray-90', data: '#222' },
      { label: '--color-gray-100', data: '#000' },
      { label: '--color-gray-110', data: '#f0f3f5' },
      { label: '--color-semantic-success', data: '#009220' },
      { label: '--color-semantic-success10', data: '#8edc51' },
      { label: '--color-semantic-success20', data: '#eefbe5' },
      { label: '--color-semantic-danger', data: '#ff5c00' },
      { label: '--color-semantic-danger10', data: '#ff8541' },
      { label: '--color-semantic-danger20', data: '#ffe1d0' },
      { label: '--color-semantic-warning', data: '#ffb800' },
      { label: '--color-semantic-warning10', data: '#fee500' },
      { label: '--color-semantic-warning20', data: '#fff8e0' },
      { label: '--color-semantic-required', data: '#d80d19' },
      { label: '--color-semantic-currentday', data: '#5d4d3d' },
      { label: '--color-semantic-info', data: '#909399' },
      { label: '--color-semantic-info10', data: '#ddd' },
      { label: '--color-semantic-info20', data: '#f1f1f1' },
      { label: '--color-header-icon-default', data: '#3b3735' },
      { label: '--color-header-dropdownmenu-item-background-hover', data: '#fff8e0' },
      { label: '--color-header-dropdownmenu-item-font-default', data: '#8e5c12' },
      { label: '--color-header-dropdownmenu-item-font-hover', data: '#5e4d3d' },
      { label: '--color-dropdownmenu-item-background-hover', data: '#f1f1f1' },
      { label: '--color-dropdownmenu-item-font-default', data: '#606266' },
      { label: '--color-dropdownmenu-item-font-hover', data: '#222' },
      { label: '--color-dropdownmenu-item-font-disabled', data: '#909399' },
      { label: '--color-avatar-name-font', data: '#000' },
      { label: '--color-breadcrumb-icon-default', data: '#606266' },
      { label: '--color-breadcrumb-font-active', data: '#3b3735' },
      { label: '--color-breadcrumb-font-default', data: '#909399' },
      { label: '--color-breadcrumb-font-hover', data: '#3b3735' },
      { label: '--color-tags-item-background-default', data: '#e8e8e8' },
      { label: '--color-tags-item-background-active', data: '#ffb800' },
      { label: '--color-tags-item-font-active', data: '#000' },
      { label: '--color-tags-item-font-default', data: '#000' },
      { label: '--color-tags-item-border-active', data: '#ffb800' },
      { label: '--color-tags-item-border-default', data: '#e8e8e8' },
      { label: '--color-tags-item-close-border-default', data: '#909399' },
      { label: '--color-tags-item-close-background-default', data: '#fff' },
      { label: '--color-tags-item-close-background-selected', data: '#d98912' },
      { label: '--color-tags-contextmenu-border-color', data: '#ddd' },
      { label: '--color-tags-contextmenu-background-color-hover', data: '#fee500' },
      { label: '--color-button-default-background-hover', data: '#ffbf85' },
      { label: '--color-button-default-background-default', data: '#f1f1f1' },
      { label: '--color-button-default-background-disabled', data: '#f1f1f1' },
      { label: '--color-button-default-font-disabled', data: '#909399' },
      { label: '--color-button-lookup-default', data: '#ffb800' },
      { label: '--color-confirm-border-default', data: '#ffefb5' },
      { label: '--color-confirm-header-border', data: '#5e4d3d' },
      { label: '--color-confirm-title', data: '#5e4d3d' },
      { label: '--color-confirm-button-confirm-background-default', data: '#fee500' },
      { label: '--color-confirm-button-confirm-border-default', data: '#ffb800' },
      { label: '--color-confirm-button-confirm-font-default', data: '#3b3735' },
      { label: '--color-confirm-button-cancel-border-default', data: '#ddd' },
      { label: '--color-confirm-button-cancel-font-default', data: '#909399' },
      { label: '--color-form-button-font-default', data: '#000' },
      { label: '--color-form-button-font-disabled', data: '#909399' },
      { label: '--color-form-button-font-hover', data: '#000' },
      { label: '--color-form-button-border-default', data: '#e8e8e8' },
      { label: '--color-form-button-border-disabled', data: '#e8e8e8' },
      { label: '--color-form-button-border-hover', data: '#e8e8e8' },
      { label: '--color-form-button-background-default', data: '#fff' },
      { label: '--color-form-button-background-disabled', data: '#f1f1f1' },
      { label: '--color-form-button-background-hover', data: '#ffb800' },
      { label: '--color-input-background-disabled', data: '#f1f1f1' },
      { label: '--color-input-border-default', data: '#e8e8e8' },
      { label: '--color-input-border-hover', data: '#ffb800' },
      { label: '--color-input-border-disabled', data: '#e8e8e8' },
      { label: '--color-radio-border-checked', data: '#ffb800' },
      { label: '--color-radio-border-default', data: '#ddd' },
      { label: '--color-radio-pseudo-background-checked', data: '#ffb800' },
      { label: '--color-radio-pseudo-background-default', data: '#ddd' },
      { label: '--color-checkbox-border-checked', data: '#ffb800' },
      { label: '--color-checkbox-border-both', data: '#ffb800' },
      { label: '--color-checkbox-background-both', data: '#ffb800' },
      { label: '--color-checkbox-background-checked', data: '#ffb800' },
      { label: '--color-checkbox-pseudo-border-checked', data: '#000' },
      { label: '--color-checkbox-pseudo-border-both', data: '#000' },
      { label: '--color-tab-border-default', data: '#5e4d3d' },
      { label: '--color-tab-item-background-selected', data: '#ffb800' },
      { label: '--color-tab-item-background-default', data: '#f6f6f6' },
      { label: '--color-tab-item-background-hover', data: '#ffb800' },
      { label: '--color-tab-item-background-extension-depth1', data: '#5e4d3d' },
      { label: '--color-tab-item-background-extension-depth2', data: '#8e5c12' },
      { label: '--color-tab-item-border-selected', data: '#ffb800' },
      { label: '--color-tab-item-border-default', data: '#e8e8e8' },
      { label: '--color-tab-item-border-hover', data: '#ffb800' },
      { label: '--color-tab-item-border-extension-depth1', data: '#5e4d3d' },
      { label: '--color-tab-item-border-extension-depth2', data: '#8e5c12' },
      { label: '--color-tab-item-font-selected', data: '#3b3735' },
      { label: '--color-tab-item-font-default', data: '#909399' },
      { label: '--color-tab-item-font-hover', data: '#76400b' },
      { label: '--color-tab-item-font-extension-default', data: '#909399' },
      { label: '--color-tab-item-font-extension-selected', data: '#fff' },
      { label: '--color-comment-border-default', data: '#e8e8e8' },
      { label: '--color-comment-more-button-background-hover', data: '#f6f6f6' },
      { label: '--color-popup-header-background', data: '#fff8e0' },
      { label: '--color-timeline-item-tail', data: '#e8e8e8' },
      { label: '--color-timeline-item-title-color-default', data: '#909399' },
      { label: '--color-timeline-item-content-color-default', data: '#606266' },
      { label: '--color-step-success', data: '#8e5c12' },
      { label: '--color-step-process', data: '#ffb800' },
      { label: '--color-step-wait', data: '#c1c4cc' },
      { label: '--color-theme-primary', data: '#ffb800' },
      { label: '--color-select-dropdown-background-hover', data: '#fffdf5' },
      { label: '--color-select-dropdown-background-selected', data: '#fff8e0' },
      { label: '--color-select-dropdown-font-default', data: '#909399' },
      { label: '--color-select-dropdown-font-selected', data: '#5e4d3d' },
      { label: '--color-select-dropdown-font-hover', data: '#606266' },
      { label: '--color-select-dropdown-font-disabled', data: '#909399' },
      { label: '--color-anchor-font-default', data: '#d98912' },
      { label: '--color-anchor-font-hover', data: '#ffb800' },
      { label: '--color-anchor-font-visited', data: '#76400b' },
      { label: '--color-list-cell-border-default', data: '#e8e8e8' },
      { label: '--color-list-head-leaf-border-bottom', data: '#ddd' },
      { label: '--color-list-head-cell-searched-font-default', data: '#fee500' },
      { label: '--color-list-head-cell-sort-font-default', data: '#fff' },
      { label: '--color-list-head-cell-sort-font-selected', data: '#ffb800' },
      { label: '--color-list-head-cell-background-default', data: '#5e4d3d' },
      { label: '--color-list-head-cell-font-default', data: '#fff' },
      { label: '--color-list-body-cell-background-default', data: '#f6f6f6' },
      { label: '--color-list-body-cell-background-hover', data: '#ffefb5' },
      { label: '--color-list-body-cell-background-selected', data: '#fdd95c' },
      { label: '--color-list-body-cell-background-subtotal', data: '#ddd' },
      { label: '--color-list-body-cell-empty-font-default', data: '#e8e8e8' },
      { label: '--color-list-body-cell-required-font-default', data: '#d80d19' },
      { label: '--color-list-body-cell-total-font-default', data: '#000' },
      { label: '--color-list-body-cell-progress-border-default', data: '#ddd' },
      { label: '--color-list-body-cell-progress-background-default', data: '#ffb800' },
      { label: '--color-list-body-cell-rating-default', data: '#ddd' },
      { label: '--color-list-body-cell-rating-active', data: '#d98912' },
      { label: '--color-list-pager-selected', data: '#ffb800' },
      { label: '--color-list-loading-stroke', data: '#8e5c12' },
      { label: '--color-list-footer-cell-background-default', data: '#fdd95c' },
      { label: '--color-alert-info-border-default', data: '#ddd' },
      { label: '--color-alert-info-font-default', data: '#909399' },
      { label: '--color-alert-info-background-default', data: '#f1f1f1' },
      { label: '--color-alert-success-border-default', data: '#8edc51' },
      { label: '--color-alert-success-font-default', data: '#009220' },
      { label: '--color-alert-success-background-default', data: '#eefbe5' },
      { label: '--color-alert-warning-border-default', data: '#fee500' },
      { label: '--color-alert-warning-font-default', data: '#ffb800' },
      { label: '--color-alert-warning-background-default', data: '#fff8e0' },
      { label: '--color-alert-danger-border-default', data: '#ff8541' },
      { label: '--color-alert-danger-font-default', data: '#ff5c00' },
      { label: '--color-alert-danger-background-default', data: '#ffe1d0' },
      { label: '--color-datepicker-highlight', data: '#0d6b49' },
      { label: '--color-datepicker-event-default', data: '#009220' },
      { label: '--color-schedule-current-date', data: '#5d4d3d' },
      { label: '--color-sidebar-background-default', data: '#3b3735' },
      { label: '--color-sidebar-menu-border-default', data: '#222' },
      { label: '--color-sidebar-collapse-title-font-default', data: '#000' },
      { label: '--color-sidebar-collapse-title-background-default', data: '#ffb800' },
      { label: '--color-sidebar-collapse-menu-background-hover', data: '#3b3735' },
      { label: '--color-sidebar-collapse-menu-background-default', data: '#606266' },
      { label: '--color-sidebar-depth1-color-default', data: '#fff' },
      { label: '--color-sidebar-depth1-color-select', data: '#fff' },
      { label: '--color-sidebar-depth1-background-default', data: '#3b3735' },
      { label: '--color-sidebar-depth2-color-default', data: '#fff' },
      { label: '--color-sidebar-depth2-color-select', data: '#ffb800' },
      { label: '--color-sidebar-depth2-edge', data: '#8e5c12' },
      { label: '--color-sidebar-depth2-background-default', data: '#45413f' },
      { label: '--color-sidebar-depth3-color-default', data: '#fff' },
      { label: '--color-sidebar-depth3-color-select', data: '#ffb800' },
      { label: '--color-sidebar-depth3-edge', data: '#d98912' },
      { label: '--color-sidebar-depth3-background-default', data: '#4f4b49' },
      { label: '--color-sidebar-depth4-color-default', data: '#fff' },
      { label: '--color-sidebar-depth4-color-select', data: '#ffb800' },
      { label: '--color-sidebar-depth4-edge', data: '#ffb800' },
      { label: '--color-sidebar-depth4-background-default', data: '#585553' },
      { label: '--color-sidebar-depth5-color-default', data: '#fff' },
      { label: '--color-sidebar-depth5-color-select', data: '#ffb800' },
      { label: '--color-sidebar-depth5-edge', data: '#ffefb5' },
      { label: '--color-sidebar-depth5-background-default', data: '#5d5b5a' },
      { label: '--color-kanban-background', data: '#f1f1f1' },
      { label: '--color-kanban-header-background', data: '#ffb800' },
      { label: '--color-kanban-header-title', data: '#3b3735' },
      { label: '--color-kanban-header-count', data: '#8e5c12' },
      { label: '--color-kanban-card-content', data: '#000' },
      { label: '--color-kanban-card-tags-background', data: '#ffefb5' },
      { label: '--color-kanban-card-tags-default', data: '#000' },
      { label: '--color-right-panel-background', data: '#f6f6f6' },
      { label: '--color-bottom-panel-background', data: '#f6f6f6' },
      { label: '--color-bottom-panel-border', data: '#c1c4cc' },
      { label: '--color-label-edge-background', data: '#909399' },
      { label: '--color-fileupload-desc-font', data: '#909399' },
      { label: '--color-fileupload-border', data: '#e8e8e8' },
      { label: '--color-fileupload-info-font', data: '#000' },
      { label: '--color-fileupload-info-file-open-font', data: '#8e5c12' },
      { label: '--color-fileupload-info-progress-background', data: '#c1c4cc' },
      { label: '--color-image-view-background', data: '#fffdf5' },
      { label: '--color-box-label', data: '#c1c4cc' },
      { label: '--color-box-icon-background', data: '#fff8e0' },
      { label: '--color-tree-button-default', data: '#ffb800' },
      { label: '--color-component-title-border', data: '#5e4d3d' },
      { label: '--color-component-title-arrow-color', data: '#909399' },
      { label: '--color-app-wrapper-background', data: '#f1f1f1' },
      { label: '--color-inlineedittoolbar-icon-new', data: '#00c2ff' },
      { label: '--color-inlineedittoolbar-icon-edit', data: '#06f' },
      { label: '--color-inlineedittoolbar-icon-delete', data: '#ff5c00' },
      { label: '--color-inlineedittoolbar-icon-save', data: '#0d6b49' },
      { label: '--color-inlineedittoolbar-icon-cancel', data: '#68686f' },
      { label: '--color-sitemap-menu-search-border-focus', data: '#c1c4cc' },
      { label: '--color-sitemap-menu-search-font', data: '#d80d19' },
      { label: '--color-sitemap-menu-match-font', data: '#222' },
      { label: '--color-secondary-10', data: '#45413f' },
      { label: '--color-secondary-20', data: '#4f4b49' },
      { label: '--color-secondary-30', data: '#585553' },
      { label: '--color-secondary-40', data: '#5d5b5a' },
      { label: '--color-secondary-50', data: '#fdd95c' },
      { label: '--color-secondary-60', data: '#ffbf85' },
      { label: '--color-notification-icon-count-background-color', data: '#d80d19' },
      { label: '--color-notification-item-urgent-background-color', data: '#ffb800' },
      { label: '--color-notification-item-urgent-border-color', data: '#e8e8e8' },
      { label: '--color-notification-item-icon-check-receipt-color', data: '#76400b' },
      { label: '--color-notification-popup-item-urgent-background-color', data: '#fdd95c' },
      { label: '--color-focus-border', data: '#8e5c12' },
      { label: '--color-required-border', data: '#d80d19' },
      { label: '--color-font-default', data: '#000' },
      { label: '--spacing-list-cell-y', data: '4.5px' },
      { label: '--spacing-gap-xs', data: '4.5px' },
      { label: '--spacing-gap-s', data: '5px' },
      { label: '--spacing-tab-item-margin-left', data: '5px' },
      { label: '--fontweight-500', data: '500' },
      { label: '--fontweight-list-body-row-selected', data: '500' },
    ],
  },
  {
    span: 8,
    themeName: 'CALS(green_2)',
    themeColorData: [
      { label: '--color-primary-10', data: '#f1fce5' },
      { label: '--color-primary-20', data: '#d0f4ac' },
      { label: '--color-primary-30', data: '#afec73' },
      { label: '--color-primary-40', data: '#8fe439' },
      { label: '--color-primary-50', data: '#6edc00' },
      { label: '--color-primary-60', data: '#5ac10c' },
      { label: '--color-primary-70', data: '#46a617' },
      { label: '--color-primary-80', data: '#328a23' },
      { label: '--color-primary-90', data: '#1e6f2e' },
      { label: '--color-primary-100', data: '#0a543a' },
      { label: '--color-icon-10', data: '#00c2ff' },
      { label: '--color-icon-20', data: '#06f' },
      { label: '--color-icon-30', data: '#ff5c00' },
      { label: '--color-icon-40', data: '#0d6b49' },
      { label: '--color-icon-50', data: '#68686f' },
      { label: '--color-icon-60', data: '#ffce00' },
      { label: '--color-gray-10', data: '#fff' },
      { label: '--color-gray-20', data: '#f6f6f6' },
      { label: '--color-gray-30', data: '#f1f1f1' },
      { label: '--color-gray-40', data: '#e8e8e8' },
      { label: '--color-gray-50', data: '#ddd' },
      { label: '--color-gray-60', data: '#c1c4cc' },
      { label: '--color-gray-70', data: '#909399' },
      { label: '--color-gray-80', data: '#606266' },
      { label: '--color-gray-90', data: '#222' },
      { label: '--color-gray-100', data: '#000' },
      { label: '--color-gray-110', data: '#f0f3f5' },
      { label: '--color-semantic-success', data: '#009220' },
      { label: '--color-semantic-success10', data: '#8edc51' },
      { label: '--color-semantic-success20', data: '#eefbe5' },
      { label: '--color-semantic-danger', data: '#ff5c00' },
      { label: '--color-semantic-danger10', data: '#ff8541' },
      { label: '--color-semantic-danger20', data: '#ffe1d0' },
      { label: '--color-semantic-warning', data: '#ffb800' },
      { label: '--color-semantic-warning10', data: '#fee500' },
      { label: '--color-semantic-warning20', data: '#fff8e0' },
      { label: '--color-semantic-required', data: '#d80d19' },
      { label: '--color-semantic-currentday', data: '#5d4d3d' },
      { label: '--color-semantic-info', data: '#909399' },
      { label: '--color-semantic-info10', data: '#ddd' },
      { label: '--color-semantic-info20', data: '#f1f1f1' },
      { label: '--color-header-icon-default', data: '#0a543a' },
      { label: '--color-header-dropdownmenu-item-background-hover', data: '#f1fce5' },
      { label: '--color-header-dropdownmenu-item-font-default', data: '#1e6f2e' },
      { label: '--color-header-dropdownmenu-item-font-hover', data: '#606266' },
      { label: '--color-breadcrumb-font-active', data: '#0a543a' },
      { label: '--color-breadcrumb-font-default', data: '#909399' },
      { label: '--color-breadcrumb-font-hover', data: '#0a543a' },
      { label: '--color-tags-item-background-active', data: '#328a23' },
      { label: '--color-tags-item-font-active', data: '#fff' },
      { label: '--color-tags-item-font-default', data: '#000' },
      { label: '--color-tags-item-border-active', data: '#328a23' },
      { label: '--color-tags-item-border-default', data: '#e8e8e8' },
      { label: '--color-tags-item-close-border-default', data: '#909399' },
      { label: '--color-tags-item-close-background-default', data: '#fff' },
      { label: '--color-tags-item-close-background-selected', data: '#328a23' },
      { label: '--color-tags-contextmenu-border-color', data: '#ddd' },
      { label: '--color-tags-contextmenu-background-color-hover', data: '#8fe439' },
      { label: '--color-button-default-background-hover', data: '#ffbf85' },
      { label: '--color-button-default-background-default', data: '#f1f1f1' },
      { label: '--color-button-default-background-diabled', data: '#f1f1f1' },
      { label: '--color-button-lookup-default', data: '#5ac10c' },
      { label: '--color-confirm-border-default', data: '#afec73' },
      { label: '--color-confirm-header-border', data: '#1e6f2e' },
      { label: '--color-confirm-title', data: '#1e6f2e' },
      { label: '--color-confirm-button-confirm-background-default', data: '#5ac10c' },
      { label: '--color-confirm-button-confirm-border-default', data: '#328a23' },
      { label: '--color-confirm-button-confirm-font-default', data: '#fff' },
      { label: '--color-form-button-font-default', data: '#0a543a' },
      { label: '--color-form-button-font-disabled', data: '#909399' },
      { label: '--color-form-button-font-hover', data: '#000' },
      { label: '--color-form-button-background-disabled', data: '#f1f1f1' },
      { label: '--color-form-button-background-hover', data: '#6edc00' },
      { label: '--color-form-button-border-default', data: '#e8e8e8' },
      { label: '--color-form-button-border-disabled', data: '#e8e8e8' },
      { label: '--color-form-button-border-hover', data: '#e8e8e8' },
      { label: '--color-input-background-disabled', data: '#f1f1f1' },
      { label: '--color-input-border-default', data: '#e8e8e8' },
      { label: '--color-input-border-hover', data: '#6edc00' },
      { label: '--color-input-border-disabled', data: '#e8e8e8' },
      { label: '--color-required-border', data: '#d80d19' },
      { label: '--color-radio-border-checked', data: '#5ac10c' },
      { label: '--color-radio-border-default', data: '#ddd' },
      { label: '--color-radio-pseudo-background-checked', data: '#5ac10c' },
      { label: '--color-checkbox-border-checked', data: '#5ac10c' },
      { label: '--color-checkbox-border-both', data: '#5ac10c' },
      { label: '--color-checkbox-background-both', data: '#5ac10c' },
      { label: '--color-checkbox-background-checked', data: '#5ac10c' },
      { label: '--color-checkbox-pseudo-border-checked', data: '#000' },
      { label: '--color-tab-border-default', data: '#1e6f2e' },
      { label: '--color-tab-item-background-selected', data: '#328a23' },
      { label: '--color-tab-item-background-default', data: '#f6f6f6' },
      { label: '--color-tab-item-background-hover', data: '#5ac10c' },
      { label: '--color-tab-item-background-extension-depth1', data: '#1e6f2e' },
      { label: '--color-tab-item-background-extension-depth2', data: '#46a617' },
      { label: '--color-tab-item-border-selected', data: '#328a23' },
      { label: '--color-tab-item-border-default', data: '#e8e8e8' },
      { label: '--color-tab-item-border-hover', data: '#5ac10c' },
      { label: '--color-tab-item-border-extension-depth1', data: '#1e6f2e' },
      { label: '--color-tab-item-border-extension-depth2', data: '#46a617' },
      { label: '--color-tab-item-font-selected', data: '#fff' },
      { label: '--color-tab-item-font-default', data: '#909399' },
      { label: '--color-tab-item-font-hover', data: '#1e6f2e' },
      { label: '--color-tab-item-font-extension-default', data: '#909399' },
      { label: '--color-tab-item-font-extension-selected', data: '#fff' },
      { label: '--color-comment-border-default', data: '#e8e8e8' },
      { label: '--color-popup-header-background', data: '#f1fce5' },
      { label: '--color-timeline-item-tail', data: '#e8e8e8' },
      { label: '--color-timeline-item-title-color-default', data: '#909399' },
      { label: '--color-timeline-item-content-color-default', data: '#606266' },
      { label: '--color-step-success', data: '#46a617' },
      { label: '--color-step-process', data: '#6edc00' },
      { label: '--color-step-wait', data: '#c1c4cc' },
      { label: '--color-theme-primary', data: '#6edc00' },
      { label: '--color-select-dropdown-background-hover', data: '#f1fce5' },
      { label: '--color-select-dropdown-background-selected', data: '#d0f4ac' },
      { label: '--color-select-dropdown-font-default', data: '#909399' },
      { label: '--color-select-dropdown-font-selected', data: '#1e6f2e' },
      { label: '--color-select-dropdown-font-hover', data: '#606266' },
      { label: '--color-select-dropdown-font-disabled', data: '#909399' },
      { label: '--color-anchor-font-default', data: '#46a617' },
      { label: '--color-anchor-font-hover', data: '#5ac10c' },
      { label: '--color-anchor-font-visited', data: '#1e6f2e' },
      { label: '--color-list-cell-border-default', data: '#e8e8e8' },
      { label: '--color-list-head-leaf-border-bottom', data: '#ddd' },
      { label: '--color-list-head-cell-searched-font-default', data: '#8fe439' },
      { label: '--color-list-head-cell-sort-font-default', data: '#fff' },
      { label: '--color-list-head-cell-sort-font-selected', data: '#8fe439' },
      { label: '--color-list-head-cell-background-default', data: '#0a543a' },
      { label: '--color-list-head-cell-font-default', data: '#fff' },
      { label: '--color-list-body-cell-background-default', data: '#fff' },
      { label: '--color-list-body-cell-background-hover', data: '#f1fce5' },
      { label: '--color-list-body-cell-background-selected', data: '#d0f4ac' },
      { label: '--color-list-body-cell-background-subtotal', data: '#ddd' },
      { label: '--color-list-body-cell-empty-font-default', data: '#e8e8e8' },
      { label: '--color-list-body-cell-required-font-default', data: '#d80d19' },
      { label: '--color-list-body-cell-total-font-default', data: '#000' },
      { label: '--color-list-body-cell-progress-border-default', data: '#ddd' },
      { label: '--color-list-body-cell-progress-background-default', data: '#6edc00' },
      { label: '--color-list-body-cell-rating-default', data: '#ddd' },
      { label: '--color-list-body-cell-rating-active', data: '#5ac10c' },
      { label: '--color-list-body-cell-font-default', data: '#000' },
      { label: '--color-list-pager-selected', data: '#46a617' },
      { label: '--color-list-loading-stroke', data: '#46a617' },
      { label: '--color-list-footer-cell-background-default', data: '#dde5d5' },
      { label: '--color-alert-info-border-default', data: '#ddd' },
      { label: '--color-alert-info-font-default', data: '#909399' },
      { label: '--color-alert-info-background-default', data: '#f1f1f1' },
      { label: '--color-alert-success-border-default', data: '#8edc51' },
      { label: '--color-alert-success-font-default', data: '#009220' },
      { label: '--color-alert-success-background-default', data: '#eefbe5' },
      { label: '--color-alert-warning-border-default', data: '#fee500' },
      { label: '--color-alert-warning-font-default', data: '#ffb800' },
      { label: '--color-alert-warning-background-default', data: '#fff8e0' },
      { label: '--color-alert-danger-border-default', data: '#ff8541' },
      { label: '--color-alert-danger-font-default', data: '#ff5c00' },
      { label: '--color-alert-danger-background-default', data: '#ffe1d0' },
      { label: '--color-datepicker-highlight', data: '#0d6b49' },
      { label: '--color-datepicker-event-highlight', data: '#009220' },
      { label: '--color-schedule-current-date', data: '#5d4d3d' },
      { label: '--color-sidebar-background-default', data: '#fff' },
      { label: '--color-sidebar-menu-border-default', data: '#f1f1f1' },
      { label: '--color-sidebar-collapse-title-font-default', data: '#fff' },
      { label: '--color-sidebar-collapse-title-background-default', data: '#328a23' },
      { label: '--color-sidebar-collapse-menu-background-hover', data: '#fafbfa' },
      { label: '--color-sidebar-collapse-menu-background-default', data: '#fff' },
      { label: '--color-sidebar-depth1-color-default', data: '#606266' },
      { label: '--color-sidebar-depth1-color-select', data: '#606266' },
      { label: '--color-sidebar-depth1-background-default', data: '#fff' },
      { label: '--color-sidebar-depth2-color-default', data: '#606266' },
      { label: '--color-sidebar-depth2-color-select', data: '#46a617' },
      { label: '--color-sidebar-depth2-edge', data: '#afec73' },
      { label: '--color-sidebar-depth2-background-default', data: '#fafbfa' },
      { label: '--color-sidebar-depth3-color-default', data: '#606266' },
      { label: '--color-sidebar-depth3-color-select', data: '#46a617' },
      { label: '--color-sidebar-depth3-edge', data: '#6edc00' },
      { label: '--color-sidebar-depth3-background-default', data: '#fafbfa' },
      { label: '--color-sidebar-depth4-color-default', data: '#606266' },
      { label: '--color-sidebar-depth4-color-select', data: '#46a617' },
      { label: '--color-sidebar-depth4-edge', data: '#46a617' },
      { label: '--color-sidebar-depth4-background-default', data: '#fafbfa' },
      { label: '--color-sidebar-depth5-color-default', data: '#606266' },
      { label: '--color-sidebar-depth5-color-select', data: '#46a617' },
      { label: '--color-sidebar-depth5-edge', data: '#328a23' },
      { label: '--color-sidebar-depth5-background-default', data: '#fafbfa' },
      { label: '--color-kanban-background', data: '#f1f1f1' },
      { label: '--color-kanban-header-background', data: '#5ac10c' },
      { label: '--color-kanban-header-title', data: '#000' },
      { label: '--color-kanban-header-count', data: '#1e6f2e' },
      { label: '--color-kanban-card-content', data: '#000' },
      { label: '--color-kanban-card-tags-background', data: '#d0f4ac' },
      { label: '--color-kanban-card-tags-default', data: '#000' },
      { label: '--color-right-panel-background', data: '#f6f6f6' },
      { label: '--color-bottom-panel-background', data: '#f6f6f6' },
      { label: '--color-bottom-panel-border', data: '#c1c4cc' },
      { label: '--color-label-edge-background', data: '#909399' },
      { label: '--color-fileupload-desc-font', data: '#909399' },
      { label: '--color-fileupload-border', data: '#e8e8e8' },
      { label: '--color-fileupload-info-font', data: '#000' },
      { label: '--color-fileupload-info-file-open-font', data: '#46a617' },
      { label: '--color-fileupload-info-progress-background', data: '#c1c4cc' },
      { label: '--color-image-view-background', data: '#ebf0e6' },
      { label: '--color-box-label', data: '#c1c4cc' },
      { label: '--color-box-icon-background', data: '#d0f4ac' },
      { label: '--color-tree-button-default', data: '#5ac10c' },
      { label: '--color-component-title-border', data: '#1e6f2e' },
      { label: '--color-component-title-arrow-color', data: '#909399' },
      { label: '--color-app-wrapper-background', data: '#f1f1f1' },
      { label: '--color-inlineedittoolbar-icon-new', data: '#00c2ff' },
      { label: '--color-inlineedittoolbar-icon-edit', data: '#06f' },
      { label: '--color-inlineedittoolbar-icon-delete', data: '#ff5c00' },
      { label: '--color-inlineedittoolbar-icon-save', data: '#0d6b49' },
      { label: '--color-inlineedittoolbar-icon-cancel', data: '#68686f' },
      { label: '--color-sitemap-menu-search-border-focus', data: '#c1c4cc' },
      { label: '--color-sitemap-menu-search-font', data: '#d80d19' },
      { label: '--color-sitemap-menu-match-font', data: '#222' },
      { label: '--color-secondary-10', data: '#fafbfa' },
      { label: '--color-secondary-20', data: '#ebf0e6' },
      { label: '--color-secondary-30', data: '#dde5d5' },
      { label: '--color-secondary-40', data: '#ffb800' },
      { label: '--color-secondary-50', data: '#fdd95c' },
      { label: '--color-secondary-60', data: '#ffbf85' },
      { label: '--color-notification-icon-count-background-color', data: '#d80d19' },
      { label: '--color-notification-item-urgent-background-color', data: '#ffb800' },
      { label: '--color-notification-item-urgent-border-color', data: '#e8e8e8' },
      { label: '--color-notification-item-icon-check-receipt-color', data: '#0a543a' },
      { label: '--color-notification-popup-item-urgent-background-color', data: '#fdd95c' },
      { label: '--color-focus-border', data: '#46a617' },
      { label: '--color-font-default', data: '#000' },
      { label: '--spacing-list-cell-y', data: '4.5px' },
      { label: '--spacing-gap-xs', data: '4.5px' },
      { label: '--spacing-gap-s', data: '5px' },
      { label: '--spacing-tab-item-margin-left', data: '5px' },
      { label: '--fontweight-500', data: 500 },
      { label: '--fontweight-list-body-row-selected', data: 500 },
    ],
  },
]
</script>

<template>
  <el-row class="ev-screen-row" :gutter="16">
    <el-col class="ev-screen-col" v-for="themeColorGroupItem in themeColorGroup" :span="themeColorGroupItem.span">
      <div class="ev-component" :class="{ 'is-folder': AppSetting.componentType == 'folder' }">
        <h4>{{ themeColorGroupItem.themeName }}</h4>
        <el-row>
          <el-col v-for="(themeColorDataItem, idx) in themeColorGroupItem.themeColorData">
            <p>
              <span class="form-num">{{ idx + 1 }}</span>
              <span class="form-label">{{ themeColorDataItem.label }} :</span>
              <span class="form-data">{{ themeColorDataItem.data }};</span>
              <span class="form-color" :style="{ 'background-color': themeColorDataItem.data }"></span>
            </p>
          </el-col>
        </el-row>
      </div>
    </el-col>
  </el-row>
</template>

<style lang="scss" scoped>
p {
  display: flex;
  justify-content: space-between;
  padding: 5px 0;
  margin: initial; 

  span {
    font-size: var(--el-font-size-base);

    &.form-num {
      width: 40px;
    }

    &.form-label {
      flex: 2;
    }

    &.form-data {
      flex: 1;
    }

    &.form-color {
      width: var(--el-component-size);
      height: 15px;
      border: 1px solid lightgray;
    }
  }
}
</style>
