<script lang="ts" setup>
const formData = [
  {
    tableName: 'Element Plus',
    tableData: [
      { span: 12, label: '--el-color-white', data: '#ffffff' },
      { span: 12, label: '--el-color-black', data: '#000000' },
      { span: 12, label: '--el-color-primary', data: '#409eff' },
      { span: 12, label: '--el-color-primary-light-3', data: '#79bbff' },
      { span: 12, label: '--el-color-primary-light-5', data: '#a0cfff' },
      { span: 12, label: '--el-color-primary-light-7', data: '#c6e2ff' },
      { span: 12, label: '--el-color-primary-light-8', data: '#d9ecff' },
      { span: 12, label: '--el-color-primary-light-9', data: '#ecf5ff' },
      { span: 12, label: '--el-color-primary-dark-2', data: '#337ecc' },
      { span: 12, label: '--el-color-success', data: '#67c23a' },
      { span: 12, label: '--el-color-success-light-3', data: '#95d475' },
      { span: 12, label: '--el-color-success-light-5', data: '#b3e19d' },
      { span: 12, label: '--el-color-success-light-7', data: '#d1edc4' },
      { span: 12, label: '--el-color-success-light-8', data: '#e1f3d8' },
      { span: 12, label: '--el-color-success-light-9', data: '#f0f9eb' },
      { span: 12, label: '--el-color-success-dark-2', data: '#529b2e' },
      { span: 12, label: '--el-color-warning', data: '#e6a23c' },
      { span: 12, label: '--el-color-warning-light-3', data: '#eebe77' },
      { span: 12, label: '--el-color-warning-light-5', data: '#f3d19e' },
      { span: 12, label: '--el-color-warning-light-7', data: '#f8e3c5' },
      { span: 12, label: '--el-color-warning-light-8', data: '#faecd8' },
      { span: 12, label: '--el-color-warning-light-9', data: '#fdf6ec' },
      { span: 12, label: '--el-color-warning-dark-2', data: '#b88230' },
      { span: 12, label: '--el-color-danger', data: '#f56c6c' },
      { span: 12, label: '--el-color-danger-light-3', data: '#f89898' },
      { span: 12, label: '--el-color-danger-light-5', data: '#fab6b6' },
      { span: 12, label: '--el-color-danger-light-7', data: '#fcd3d3' },
      { span: 12, label: '--el-color-danger-light-8', data: '#fde2e2' },
      { span: 12, label: '--el-color-danger-light-9', data: '#fef0f0' },
      { span: 12, label: '--el-color-danger-dark-2', data: '#c45656' },
      { span: 12, label: '--el-color-error', data: '#f56c6c' },
      { span: 12, label: '--el-color-error-light-3', data: '#f89898' },
      { span: 12, label: '--el-color-error-light-5', data: '#fab6b6' },
      { span: 12, label: '--el-color-error-light-7', data: '#fcd3d3' },
      { span: 12, label: '--el-color-error-light-8', data: '#fde2e2' },
      { span: 12, label: '--el-color-error-light-9', data: '#fef0f0' },
      { span: 12, label: '--el-color-error-dark-2', data: '#c45656' },
      { span: 12, label: '--el-color-info', data: '#909399' },
      { span: 12, label: '--el-color-info-light-3', data: '#b1b3b8' },
      { span: 12, label: '--el-color-info-light-5', data: '#c8c9cc' },
      { span: 12, label: '--el-color-info-light-7', data: '#dedfe0' },
      { span: 12, label: '--el-color-info-light-8', data: '#e9e9eb' },
      { span: 12, label: '--el-color-info-light-9', data: '#f4f4f5' },
      { span: 12, label: '--el-color-info-dark-2', data: '#73767a' },
      { span: 12, label: '--el-bg-color', data: '#ffffff' },
      { span: 12, label: '--el-bg-color-page', data: '#f2f3f5' },
      { span: 12, label: '--el-bg-color-overlay', data: '#ffffff' },
      { span: 12, label: '--el-text-color-primary', data: '#303133' },
      { span: 12, label: '--el-text-color-regular', data: '#606266' },
      { span: 12, label: '--el-text-color-secondary', data: '#909399' },
      { span: 12, label: '--el-text-color-placeholder', data: '#a8abb2' },
      { span: 12, label: '--el-text-color-disabled', data: '#c0c4cc' },
      { span: 12, label: '--el-border-color', data: '#dcdfe6' },
      { span: 12, label: '--el-border-color-light', data: '#e4e7ed' },
      { span: 12, label: '--el-border-color-lighter', data: '#ebeef5' },
      { span: 12, label: '--el-border-color-extra-light', data: '#f2f6fc' },
      { span: 12, label: '--el-border-color-dark', data: '#d4d7de' },
      { span: 12, label: '--el-border-color-darker', data: '#cdd0d6' },
      { span: 12, label: '--el-fill-color', data: '#f0f2f5' },
      { span: 12, label: '--el-fill-color-light', data: '#f5f7fa' },
      { span: 12, label: '--el-fill-color-lighter', data: '#fafafa' },
      { span: 12, label: '--el-fill-color-extra-light', data: '#fafcff' },
      { span: 12, label: '--el-fill-color-dark', data: '#ebedf0' },
      { span: 12, label: '--el-fill-color-darker', data: '#e6e8eb' },
      { span: 12, label: '--el-fill-color-blank', data: '#ffffff' },
      {
        span: 12,
        label: '--el-box-shadow',
        data: '0px 12px 32px 4px rgba(0, 0, 0, 0.04),	0px 8px 20px rgba(0, 0, 0, 0.08)',
      },
      { span: 12, label: '--el-box-shadow-light', data: '0px 0px 12px rgba(0, 0, 0, 0.12)' },
      { span: 12, label: '--el-box-shadow-lighter', data: '0px 0px 6px rgba(0, 0, 0, 0.12)' },
      {
        span: 12,
        label: '--el-box-shadow-dark',
        data: '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12), 0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
      },
      { span: 12, label: '--el-overlay-color', data: 'rgba(0, 0, 0, 0.8)' },
      { span: 12, label: '--el-overlay-color-light', data: 'rgba(0, 0, 0, 0.7)' },
      { span: 12, label: '--el-overlay-color-lighter', data: 'rgba(0, 0, 0, 0.5)' },
      { span: 12, label: '--el-mask-color', data: 'rgba(255, 255, 255, 0.9)' },
      { span: 12, label: '--el-mask-color-extra-light', data: 'rgba(255, 255, 255, 0.3)' },
      { span: 12, label: '--el-color-primary-rgb', data: '64, 158, 255' },
      { span: 12, label: '--el-color-success-rgb', data: '103, 194, 58' },
      { span: 12, label: '--el-color-warning-rgb', data: '230, 162, 60' },
      { span: 12, label: '--el-color-danger-rgb', data: '245, 108, 108' },
      { span: 12, label: '--el-color-error-rgb', data: '245, 108, 108' },
      { span: 12, label: '--el-color-info-rgb', data: '144, 147, 153' },
      { span: 12, label: '--el-font-size-extra-large', data: '20px' },
      { span: 12, label: '--el-font-size-large', data: '18px' },
      { span: 12, label: '--el-font-size-medium', data: '16px' },
      { span: 12, label: '--el-font-size-base', data: '14px' },
      { span: 12, label: '--el-font-size-small', data: '13px' },
      { span: 12, label: '--el-font-size-extra-small', data: '12px' },
      { span: 12, label: '--el-font-family', data: 'notosans, Arial, sans-serif' },
      { span: 12, label: '--el-font-weight-primary', data: '500' },
      { span: 12, label: '--el-font-line-height-primary', data: '24px' },
      { span: 12, label: '--el-index-normal', data: '1' },
      { span: 12, label: '--el-index-top', data: '1000' },
      { span: 12, label: '--el-index-popper', data: '2000' },
      { span: 12, label: '--el-border-radius-base', data: '4px' },
      { span: 12, label: '--el-border-radius-small', data: '2px' },
      { span: 12, label: '--el-border-radius-round', data: '20px' },
      { span: 12, label: '--el-border-radius-circle', data: '100%' },
      { span: 12, label: '--el-component-size-large', data: '40px' },
      { span: 12, label: '--el-component-size', data: '32px' },
      { span: 12, label: '--el-component-size-small', data: '24px' },
      { span: 12, label: '--el-popup-modal-opacity', data: '0.5' },
      { span: 12, label: '--el-loading-spinner-size', data: '42px' },
      { span: 12, label: '--el-loading-fullscreen-spinner-size', data: '50px' },
      { span: 12, label: '--el-menu-item-height', data: '56px' },
      { span: 12, label: '--el-menu-horizontal-height: 60px' },
      { span: 12, label: '--el-menu-horizontal-sub-item-height', data: '36px' },
      { span: 12, label: '--el-menu-base-level-padding', data: '20px' },
      { span: 12, label: '--el-menu-level-padding', data: '20px' },
      { span: 12, label: '--el-menu-icon-width', data: '24px' },
      { span: 12, label: '--bg-color-rgb', data: '255, 255, 255' },
      { span: 12, label: '--bg-color-soft', data: '#fafafa' },
      { span: 12, label: '--bg-color-mute', data: '#f2f2f2' },
      { span: 12, label: '--purple-color', data: '#6222c2' },
      { span: 12, label: '--purple-color-light', data: '#9065db' },
      { span: 12, label: '--header-height', data: '55px' },
      { span: 12, label: '--nav-height', data: '55px' },
      { span: 12, label: '--vp-screen-max-width', data: '1362px' },
      { span: 12, label: '--vp-sidebar-width-mobile', data: '320px' },
      { span: 12, label: '--vp-sidebar-width-small', data: '266px' },
      { span: 12, label: '--sidebar-width-sm', data: '16rem' },
      { span: 12, label: '--sidebar-width-xs', data: '20rem' },
      { span: 12, label: '--content-min-width', data: '16rem' },
      { span: 12, label: '--content-max-width', data: '48rem' },
      { span: 12, label: '--nav-z-index', data: '12' },
      { span: 12, label: '--sub-nav-z-index', data: '11' },
      { span: 12, label: '--sidebar-z-index', data: '40' },
      { span: 12, label: '--overlay-z-index', data: '30' },
      { span: 12, label: '--code-line-height', data: '1.4' },
      { span: 12, label: '--code-tooltip-color', data: '#0c61c9' },
    ],
  },
  {
    tableName: 'CALS',
    tableData: [
      { span: 12, label: '--color-primary-10', data: '#f5fafc' },
      { span: 12, label: '--color-primary-20', data: '#f4f7f8' },
      { span: 12, label: '--color-primary-30', data: '#f3f5f5' },
      { span: 12, label: '--color-primary-40', data: '#e7f3f7' },
      { span: 12, label: '--color-primary-50', data: '#dae6eb' },
      { span: 12, label: '--color-primary-60', data: '#9fcad9' },
      { span: 12, label: '--color-primary-70', data: '#5796ad' },
      { span: 12, label: '--color-primary-80', data: '#3386a2' },
      { span: 12, label: '--color-primary-90', data: '#055a78' },
      { span: 12, label: '--color-primary-100', data: '#2f657d' },
      { span: 12, label: '--color-icon-10', data: '#f3b45b' },
      { span: 12, label: '--color-icon-20', data: '#0e8bff' },
      { span: 12, label: '--color-icon-30', data: '#fe8057' },
      { span: 12, label: '--color-icon-40', data: '#2aaeb1' },
      { span: 12, label: '--color-icon-50', data: '#8c8c8c' },
      { span: 12, label: '--color-icon-60', data: '#ffce00' },
      { span: 12, label: '--color-gray-10', data: '#ffffff' },
      { span: 12, label: '--color-gray-20', data: '#f6f6f6' },
      { span: 12, label: '--color-gray-30', data: '#f1f1f1' },
      { span: 12, label: '--color-gray-40', data: '#e8e8e8' },
      { span: 12, label: '--color-gray-50', data: '#dddddd' },
      { span: 12, label: '--color-gray-60', data: '#c1c4cc' },
      { span: 12, label: '--color-gray-70', data: '#909399' },
      { span: 12, label: '--color-gray-80', data: '#606266' },
      { span: 12, label: '--color-gray-90', data: '#222222' },
      { span: 12, label: '--color-gray-100', data: '#000000' },
      { span: 12, label: '--color-gray-110', data: '#f0f3f5' },
      { span: 12, label: '--color-semantic-success', data: '#2fc898' },
      { span: 12, label: '--color-semantic-success10', data: '#6cddba' },
      { span: 12, label: '--color-semantic-success20', data: '#baf1e1' },
      { span: 12, label: '--color-semantic-danger', data: '#f56c6c' },
      { span: 12, label: '--color-semantic-danger10', data: '#feb5b6' },
      { span: 12, label: '--color-semantic-danger20', data: '#ffe4e4' },
      { span: 12, label: '--color-semantic-warning', data: '#e6a23c' },
      { span: 12, label: '--color-semantic-warning10', data: '#f2c98b' },
      { span: 12, label: '--color-semantic-warning20', data: '#fff3dd' },
      { span: 12, label: '--color-semantic-required', data: '#f75456' },
      { span: 12, label: '--color-semantic-currentday', data: '#e3165b' },
      { span: 12, label: '--color-semantic-info', data: '#909399' },
      { span: 12, label: '--color-semantic-info10', data: '#bcbec5' },
      { span: 12, label: '--color-semantic-info20', data: '#f1f1fd' },
      { span: 12, label: '--color-header-icon-default', data: '#3386a2' },
      { span: 12, label: '--color-header-background-default', data: '#ffffff' },
      { span: 12, label: '--color-header-dropdownmenu-item-background-hover', data: '#dae6eb' },
      { span: 12, label: '--color-header-dropdownmenu-item-font-default', data: '#5796ad' },
      { span: 12, label: '--color-header-dropdownmenu-item-font-hover', data: '#055a78' },
      { span: 12, label: '--color-dropdown-background-default', data: '#ffffff' },
      { span: 12, label: '--color-dropdown-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-dropdownmenu-item-background-hover', data: '#f1f1f1' },
      { span: 12, label: '--color-dropdownmenu-item-font-default', data: '#606266' },
      { span: 12, label: '--color-dropdownmenu-item-font-hover', data: '#222222' },
      { span: 12, label: '--color-dropdownmenu-item-font-disabled', data: '#909399' },
      { span: 12, label: '--color-avatar-name-font', data: '#606266' },
      { span: 12, label: '--color-breadcrumb-icon-default', data: '#606266' },
      { span: 12, label: '--color-breadcrumb-font-active', data: '#5796ad' },
      { span: 12, label: '--color-breadcrumb-font-default', data: '#222222' },
      { span: 12, label: '--color-breadcrumb-font-hover', data: '#3386a2' },
      { span: 12, label: '--color-tags-item-background-default', data: '#ffffff' },
      { span: 12, label: '--color-tags-item-background-active', data: '#9fcad9' },
      { span: 12, label: '--color-tags-item-font-active', data: '#2f657d' },
      { span: 12, label: '--color-tags-item-font-default', data: '#c1c4cc' },
      { span: 12, label: '--color-tags-item-border-active', data: '#9fcad9' },
      { span: 12, label: '--color-tags-item-border-default', data: '#ffffff' },
      { span: 12, label: '--color-tags-item-close-border-default', data: '#c1c4cc' },
      { span: 12, label: '--color-tags-item-close-border-selected', data: '#ffffff' },
      { span: 12, label: '--color-tags-item-close-background-default', data: '#ffffff' },
      { span: 12, label: '--color-tags-item-close-background-selected', data: '#9fcad9' },
      { span: 12, label: '--color-tags-contextmenu-border-color', data: '#dddddd' },
      { span: 12, label: '--color-tags-contextmenu-background-color-default', data: '#ffffff' },
      { span: 12, label: '--color-tags-contextmenu-background-color-hover', data: '#e7f3f7' },
      { span: 12, label: '--color-button-default-background-default', data: '#ffffff' },
      { span: 12, label: '--color-button-default-background-disabled', data: '#ffffff' },
      { span: 12, label: '--color-button-default-background-hover', data: '#e8e8e8' },
      { span: 12, label: '--color-button-default-font-default', data: '#000000' },
      { span: 12, label: '--color-button-default-font-disabled', data: '#909399' },
      { span: 12, label: '--color-button-default-font-hover', data: '#000000' },
      { span: 12, label: '--color-button-default-border-default', data: 'transparent' },
      { span: 12, label: '--color-button-default-border-disabled', data: 'transparent' },
      { span: 12, label: '--color-button-default-border-hover', data: 'transparent' },
      { span: 12, label: '--color-button-lookup-default', data: '#055a78' },
      { span: 12, label: '--color-confirm-border-default', data: '#e7f3f7' },
      { span: 12, label: '--color-confirm-header-border', data: '#055a78' },
      { span: 12, label: '--color-confirm-title', data: '#055a78' },
      { span: 12, label: '--color-confirm-button-confirm-background-default', data: '#e7f3f7' },
      { span: 12, label: '--color-confirm-button-confirm-border-default', data: '#dae6eb' },
      { span: 12, label: '--color-confirm-button-confirm-font-default', data: '#2f657d' },
      { span: 12, label: '--color-confirm-button-cancel-background-default', data: '#ffffff' },
      { span: 12, label: '--color-confirm-button-cancel-border-default', data: '#dddddd' },
      { span: 12, label: '--color-confirm-button-cancel-font-default', data: '#909399' },
      { span: 12, label: '--color-confirm-boxshadow', data: '#0000003d' },
      { span: 12, label: '--color-form-button-font-default', data: '#055a78' },
      { span: 12, label: '--color-form-button-font-disabled', data: '#909399' },
      { span: 12, label: '--color-form-button-font-hover', data: '#055a78' },
      { span: 12, label: '--color-form-button-border-default', data: '#e8e8e8' },
      { span: 12, label: '--color-form-button-border-disabled', data: '#e8e8e8' },
      { span: 12, label: '--color-form-button-border-hover', data: '#e8e8e8' },
      { span: 12, label: '--color-form-button-background-default', data: '#ffffff' },
      { span: 12, label: '--color-form-button-background-disabled', data: '#f1f1f1' },
      { span: 12, label: '--color-form-button-background-hover', data: '#e8e8e8' },
      { span: 12, label: '--color-input-background-default', data: '#ffffff' },
      { span: 12, label: '--color-input-background-hover', data: '#ffffff' },
      { span: 12, label: '--color-input-background-disabled', data: '#f1f1f1' },
      { span: 12, label: '--color-input-border-default', data: '#e8e8e8' },
      { span: 12, label: '--color-input-border-hover', data: '#9fcad9' },
      { span: 12, label: '--color-input-border-disabled', data: '#e8e8e8' },
      { span: 12, label: '--color-input-font-placeholder', data: '#c1c4cc' },
      { span: 12, label: '--color-input-font-disabled', data: '#606266' },
      { span: 12, label: '--color-input-font-hover', data: '#000000' },
      { span: 12, label: '--color-input-font-default', data: '#000000' },
      { span: 12, label: '--color-required-border', data: '#f75456' },
      { span: 12, label: '--color-radio-border-checked', data: '#055a78' },
      { span: 12, label: '--color-radio-border-default', data: '#c1c4cc' },
      { span: 12, label: '--color-radio-background-checked', data: '#ffffff' },
      { span: 12, label: '--color-radio-background-default', data: '#ffffff' },
      { span: 12, label: '--color-radio-pseudo-background-checked', data: '#055a78' },
      { span: 12, label: '--color-radio-pseudo-background-default', data: '#ffffff' },
      { span: 12, label: '--color-checkbox-border-checked', data: '#055a78' },
      { span: 12, label: '--color-checkbox-border-default', data: '#c1c4cc' },
      { span: 12, label: '--color-checkbox-border-disabled', data: '#c1c4cc' },
      { span: 12, label: '--color-checkbox-border-both', data: '#055a78' },
      { span: 12, label: '--color-checkbox-background-checked', data: '#ffffff' },
      { span: 12, label: '--color-checkbox-background-default', data: '#ffffff' },
      { span: 12, label: '--color-checkbox-background-disabled', data: '#f1f1f1' },
      { span: 12, label: '--color-checkbox-background-both', data: '#055a78' },
      { span: 12, label: '--color-checkbox-pseudo-border-checked', data: '#055a78' },
      { span: 12, label: '--color-checkbox-pseudo-border-default', data: '#ffffff' },
      { span: 12, label: '--color-checkbox-pseudo-border-disabled', data: '#c1c4cc' },
      { span: 12, label: '--color-checkbox-pseudo-border-both', data: '#ffffff' },
      { span: 12, label: '--color-tab-border-default', data: '#9fcad9' },
      { span: 12, label: '--color-tab-item-background-selected', data: '#9fcad9' },
      { span: 12, label: '--color-tab-item-background-default', data: '#ffffff' },
      { span: 12, label: '--color-tab-item-background-hover', data: '#ffffff' },
      { span: 12, label: '--color-tab-item-background-extension-depth1', data: '#055a78' },
      { span: 12, label: '--color-tab-item-background-extension-depth2', data: '#5796ad' },
      { span: 12, label: '--color-tab-item-border-selected', data: '#9fcad9' },
      { span: 12, label: '--color-tab-item-border-default', data: '#9fcad9' },
      { span: 12, label: '--color-tab-item-border-hover', data: '#9fcad9' },
      { span: 12, label: '--color-tab-item-border-extension-depth1', data: '#055a78' },
      { span: 12, label: '--color-tab-item-border-extension-depth2', data: '#5796ad' },
      { span: 12, label: '--color-tab-item-font-selected', data: '#055a78' },
      { span: 12, label: '--color-tab-item-font-default', data: '#606266' },
      { span: 12, label: '--color-tab-item-font-hover', data: '#3386a2' },
      { span: 12, label: '--color-tab-item-font-extension-default', data: '#909399' },
      { span: 12, label: '--color-tab-item-font-extension-selected', data: '#ffffff' },
      { span: 12, label: '--color-comment-border-default', data: '#dddddd' },
      { span: 12, label: '--color-comment-more-button-default', data: '#000000' },
      { span: 12, label: '--color-comment-more-button-background-default', data: '#ffffff' },
      { span: 12, label: '--color-comment-more-button-background-hover', data: '#f6f6f6' },
      { span: 12, label: '--color-popup-background-default', data: '#ffffff' },
      { span: 12, label: '--color-popup-header-background', data: '#f0f3f5' },
      { span: 12, label: '--color-popup-close-button-background', data: 'transparent' },
      { span: 12, label: '--color-popup-boxshadow', data: '#0000004a' },
      { span: 12, label: '--color-timeline-item-tail', data: '#e8e8e8' },
      { span: 12, label: '--color-timeline-item-backgrond-default', data: '#ffffff' },
      { span: 12, label: '--color-timeline-item-title-color-default', data: '#909399' },
      { span: 12, label: '--color-timeline-item-content-color-default', data: '#606266' },
      { span: 12, label: '--color-step-success', data: '#5796ad' },
      { span: 12, label: '--color-step-process', data: '#222222' },
      { span: 12, label: '--color-step-wait', data: '#909399' },
      { span: 12, label: '--color-theme-primary', data: '#5796ad' },
      { span: 12, label: '--color-select-dropdown-background-default', data: '#ffffff' },
      { span: 12, label: '--color-select-dropdown-background-hover', data: '#f5fafc' },
      { span: 12, label: '--color-select-dropdown-background-selected', data: '#e7f3f7' },
      { span: 12, label: '--color-select-dropdown-font-default', data: '#909399' },
      { span: 12, label: '--color-select-dropdown-font-selected', data: '#055a78' },
      { span: 12, label: '--color-select-dropdown-font-hover', data: '#606266' },
      { span: 12, label: '--color-select-dropdown-font-disabled', data: '#909399' },
      { span: 12, label: '--color-select-dropdown-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-anchor-font-default', data: '#007dbc' },
      { span: 12, label: '--color-anchor-font-hover', data: '#4bafc8b3' },
      { span: 12, label: '--color-anchor-font-visited', data: '#005b86' },
      { span: 12, label: '--color-list-cell-border-default', data: '#e8e8e8' },
      { span: 12, label: '--color-list-head-leaf-border-bottom', data: '#c1c4cc' },
      { span: 12, label: '--color-list-head-cell-searched-font-default', data: '#5796ad' },
      { span: 12, label: '--color-list-head-cell-sort-font-default', data: '#c1c4cc' },
      { span: 12, label: '--color-list-head-cell-sort-font-selected', data: '#5796ad' },
      { span: 12, label: '--color-list-head-cell-background-default', data: '#f5fafc' },
      { span: 12, label: '--color-list-head-cell-font-default', data: '#000000' },
      { span: 12, label: '--color-list-body-cell-background-default', data: '#ffffff' },
      { span: 12, label: '--color-list-body-cell-background-hover', data: '#f6f6f6' },
      { span: 12, label: '--color-list-body-cell-background-selected', data: '#e7f3f7' },
      { span: 12, label: '--color-list-body-cell-background-subtotal', data: '#dddddd' },
      { span: 12, label: '--color-list-body-cell-empty-font-default', data: '#f6f6f6' },
      { span: 12, label: '--color-list-body-cell-required-font-default', data: '#f75456' },
      { span: 12, label: '--color-list-body-cell-total-font-default', data: '#5796ad' },
      { span: 12, label: '--color-list-body-cell-progress-border-default', data: '#c1c4cc' },
      { span: 12, label: '--color-list-body-cell-progress-background-default', data: '#9fcad9' },
      { span: 12, label: '--color-list-body-cell-rating-default', data: '#dae6eb' },
      { span: 12, label: '--color-list-body-cell-rating-active', data: '#ffce00' },
      { span: 12, label: '--color-list-body-cell-font-default', data: '#000000' },
      { span: 12, label: '--color-list-pager-selected', data: '#5796ad' },
      { span: 12, label: '--color-list-pager-default', data: '#c1c4cc' },
      { span: 12, label: '--color-list-loading-stroke', data: '#5796ad' },
      { span: 12, label: '--color-list-footer-cell-background-default', data: '#f6f6f6' },
      { span: 12, label: '--color-alert-info-border-default', data: '#bcbec5' },
      { span: 12, label: '--color-alert-info-font-default', data: '#909399' },
      { span: 12, label: '--color-alert-info-background-default', data: '#f1f1fd' },
      { span: 12, label: '--color-alert-success-border-default', data: '#6cddba' },
      { span: 12, label: '--color-alert-success-font-default', data: '#2fc898' },
      { span: 12, label: '--color-alert-success-background-default', data: '#baf1e1' },
      { span: 12, label: '--color-alert-warning-border-default', data: '#f2c98b' },
      { span: 12, label: '--color-alert-warning-font-default', data: '#e6a23c' },
      { span: 12, label: '--color-alert-warning-background-default', data: '#fff3dd' },
      { span: 12, label: '--color-alert-danger-border-default', data: '#feb5b6' },
      { span: 12, label: '--color-alert-danger-font-default', data: '#f56c6c' },
      { span: 12, label: '--color-alert-danger-background-default', data: '#ffe4e4' },
      { span: 12, label: '--color-alert-boxshadow', data: '#00000059' },
      { span: 12, label: '--color-datepicker-highlight', data: '#2aaeb1' },
      { span: 12, label: '--color-datepicker-boxshadow', data: '#0000001a' },
      { span: 12, label: '--color-datepicker-event-default', data: '#2fc898' },
      { span: 12, label: '--color-font-default', data: '#000000' },
      { span: 12, label: '--color-schedule-current-date', data: '#e3165b' },
      { span: 12, label: '--color-schedule-background-default', data: '#ffffff' },
      { span: 12, label: '--color-sidebar-background-default', data: '#f4f7f8' },
      { span: 12, label: '--color-sidebar-menu-border-default', data: '#dae6eb' },
      { span: 12, label: '--color-sidebar-collapse-title-font-default', data: '#ffffff' },
      { span: 12, label: '--color-sidebar-collapse-title-background-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-collapse-menu-background-hover', data: '#f4f7f8' },
      { span: 12, label: '--color-sidebar-collapse-menu-background-default', data: '#ffffff' },
      { span: 12, label: '--color-sidebar-depth1-color-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth1-color-select', data: '#2f657d' },
      { span: 12, label: '--color-sidebar-depth1-edge', data: 'transparent' },
      { span: 12, label: '--color-sidebar-depth1-background-default', data: 'transparent' },
      { span: 12, label: '--color-sidebar-depth2-color-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth2-color-select', data: '#2f657d' },
      { span: 12, label: '--color-sidebar-depth2-edge', data: '#9fcad9' },
      { span: 12, label: '--color-sidebar-depth2-background-default', data: 'transparent' },
      { span: 12, label: '--color-sidebar-depth3-color-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth3-color-select', data: '#2f657d' },
      { span: 12, label: '--color-sidebar-depth3-edge', data: '#5796ad' },
      { span: 12, label: '--color-sidebar-depth3-background-default', data: 'transparent' },
      { span: 12, label: '--color-sidebar-depth4-color-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth4-color-select', data: '#2f657d' },
      { span: 12, label: '--color-sidebar-depth4-edge', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth4-background-default', data: 'transparent' },
      { span: 12, label: '--color-sidebar-depth5-color-default', data: '#3386a2' },
      { span: 12, label: '--color-sidebar-depth5-color-select', data: '#2f657d' },
      { span: 12, label: '--color-sidebar-depth5-edge', data: '#055a78' },
      { span: 12, label: '--color-sidebar-depth5-background-default', data: 'transparent' },
      { span: 12, label: '--color-sidebar-item-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-sidebar-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-scrollbar-default', data: '#9093994d' },
      { span: 12, label: '--color-scrollbar-hover', data: '#90939980' },
      { span: 12, label: '--color-kanban-background', data: '#f6f6f6' },
      { span: 12, label: '--color-kanban-header-background', data: '#5796ad' },
      { span: 12, label: '--color-kanban-header-title', data: '#ffffff' },
      { span: 12, label: '--color-kanban-header-count', data: '#f1f1f1' },
      { span: 12, label: '--color-kanban-card-background', data: '#ffffff' },
      { span: 12, label: '--color-kanban-card-title', data: '#000000' },
      { span: 12, label: '--color-kanban-card-content', data: '#606266' },
      { span: 12, label: '--color-kanban-card-tags-background', data: '#dae6eb' },
      { span: 12, label: '--color-kanban-card-tags-default', data: '#3386a2' },
      { span: 12, label: '--color-kanban-card-boxshadow', data: '#00000029' },
      { span: 12, label: '--color-right-panel-background', data: '#f6f6f6' },
      { span: 12, label: '--color-right-panel-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-bottom-panel-background', data: '#f6f6f6' },
      { span: 12, label: '--color-bottom-panel-border', data: '#c1c4cc' },
      { span: 12, label: '--color-bottom-panel-boxshadow', data: '#0000001f' },
      { span: 12, label: '--color-label-edge-background', data: '#909399' },
      { span: 12, label: '--color-fileupload-desc-font', data: '#909399' },
      { span: 12, label: '--color-fileupload-border', data: '#e8e8e8' },
      { span: 12, label: '--color-fileupload-info-font', data: '#606266' },
      { span: 12, label: '--color-fileupload-info-file-open-font', data: '#5796ad' },
      { span: 12, label: '--color-fileupload-info-background', data: '#ffffff' },
      { span: 12, label: '--color-fileupload-info-progress-background', data: '#c1c4cc' },
      { span: 12, label: '--color-image-view-background', data: '#f4f7f8' },
      { span: 12, label: '--color-box-label', data: '#c1c4cc' },
      { span: 12, label: '--color-box-icon-background', data: '#f4f7f8' },
      { span: 12, label: '--color-tree-button-default', data: '#055a78' },
      { span: 12, label: '--color-component-background', data: '#ffffff' },
      { span: 12, label: '--color-component-title-border', data: '#9fcad9' },
      { span: 12, label: '--color-component-title-arrow-color', data: '#606266' },
      { span: 12, label: '--color-app-wrapper-background', data: '#f3f5f5' },
      { span: 12, label: '--color-inlineedittoolbar-icon-background', data: '#ffffff' },
      { span: 12, label: '--color-inlineedittoolbar-icon-new', data: '#f3b45b' },
      { span: 12, label: '--color-inlineedittoolbar-icon-edit', data: '#0e8bff' },
      { span: 12, label: '--color-inlineedittoolbar-icon-delete', data: '#fe8057' },
      { span: 12, label: '--color-inlineedittoolbar-icon-save', data: '#2aaeb1' },
      { span: 12, label: '--color-inlineedittoolbar-icon-cancel', data: '#8c8c8c' },
      { span: 12, label: '--color-overlay-loading-font', data: '#ffffff' },
      { span: 12, label: '--color-overlay-loading-boxshadow', data: '#0000004d' },
      { span: 12, label: '--color-vfm-background', data: '#00000033' },
      { span: 12, label: '--color-sitemap-menu-search-border-focus', data: '#c1c4cc' },
      { span: 12, label: '--color-sitemap-menu-search-font', data: '#f75456' },
      { span: 12, label: '--color-sitemap-menu-match-font', data: '#ffffff' },
      { span: 12, label: '--color-sitemap-menu-font', data: '#222222' },
      { span: 12, label: '--color-secondary-10', data: '#007dbc' },
      { span: 12, label: '--color-secondary-20', data: '#4bafc8b3' },
      { span: 12, label: '--color-secondary-30', data: '#005b86' },
      { span: 12, label: '--color-secondary-40', data: '#f9fbf5' },
      { span: 12, label: '--color-secondary-50', data: '#ffffff' },
      { span: 12, label: '--color-secondary-60', data: '#ffffff' },
      { span: 12, label: '--color-notification-icon-count-color', data: '#ffffff' },
      { span: 12, label: '--color-notification-icon-count-background-color', data: '#e3165b' },
      { span: 12, label: '--color-notification-item-urgent-background-color', data: '#ffe4e4' },
      { span: 12, label: '--color-notification-item-urgent-border-color', data: '#feb5b6' },
      { span: 12, label: '--color-notification-item-icon-check-receipt-color', data: '#3386a2' },
      {
        span: 12,
        label: '--color-notification-popup-item-urgent-background-color',
        data: '#ffe4e4',
      },
      { span: 12, label: '--color-focus-border', data: '#5796ad' },
      { span: 12, label: '--fontfamily-default', data: 'notosans' },
      { span: 12, label: '--fontweight-100', data: '100' },
      { span: 12, label: '--fontweight-300', data: '300' },
      { span: 12, label: '--fontweight-400', data: '400' },
      { span: 12, label: '--fontweight-500', data: '500' },
      { span: 12, label: '--fontweight-700', data: '700' },
      { span: 12, label: '--fontweight-900', data: '900' },
      { span: 12, label: '--fontweight-default', data: '400' },
      { span: 12, label: '--fontweight-tab-item', data: '400' },
      { span: 12, label: '--fontweight-popup-title', data: '700' },
      { span: 12, label: '--fontweight-confirm-button', data: '700' },
      { span: 12, label: '--fontweight-box-label', data: '500' },
      { span: 12, label: '--fontweight-box-data', data: '700' },
      { span: 12, label: '--fontweight-button-default', data: '500' },
      { span: 12, label: '--fontweight-form-button', data: '500' },
      { span: 12, label: '--fontweight-list-cell', data: '300' },
      { span: 12, label: '--fontweight-list-header', data: '500' },
      { span: 12, label: '--fontweight-list-pager-selected', data: '500' },
      { span: 12, label: '--fontweight-list-body-row-selected', data: '300' },
      { span: 12, label: '--fontweight-input', data: '400' },
      { span: 12, label: '--fontweight-breadcrumb-default', data: '400' },
      { span: 12, label: '--fontweight-breadcrumb-active', data: '400' },
      { span: 12, label: '--fontweight-avatar-name', data: '500' },
      { span: 12, label: '--fontweight-sidebar-default', data: '400' },
      { span: 12, label: '--fontweight-sidebar-hover', data: '500' },
      { span: 12, label: '--fontweight-sidebar-selected', data: '500' },
      { span: 12, label: '--fontweight-tags-item', data: '400' },
      { span: 12, label: '--fontweight-component-title-arrow', data: '700' },
      { span: 12, label: '--fontweight-kanban-header-title', data: '500' },
      { span: 12, label: '--fontweight-kanban-card-title', data: '500' },
      { span: 12, label: '--fontweight-fileupload-desc', data: '400' },
      { span: 12, label: '--fontweight-comment-more-button', data: '500' },
      { span: 12, label: '--borderradius-default', data: '4px' },
      { span: 12, label: '--fontsize-default', data: '14px' },
      { span: 12, label: '--fontsize-xs', data: '0.75' },
      { span: 12, label: '--fontsize-2xs', data: '0.563' },
      { span: 12, label: '--fontsize-s', data: '0.875' },
      { span: 12, label: '--fontsize-m', data: '1' },
      { span: 12, label: '--fontsize-l', data: '1.15' },
      { span: 12, label: '--fontsize-xl', data: '1.25' },
      { span: 12, label: '--fontsize-2xl', data: '1.5' },
      { span: 12, label: '--fontsize-3xl', data: '3.5' },
      { span: 12, label: '--fontsize-h1', data: '78.75px' },
      { span: 12, label: '--fontsize-h2', data: '52.5px' },
      { span: 12, label: '--fontsize-h3', data: '42px' },
      { span: 12, label: '--fontsize-h4', data: '29.75px' },
      { span: 12, label: '--fontsize-h5', data: '21px' },
      { span: 12, label: '--fontsize-h6', data: '12.25px' },
      { span: 12, label: '--fontsize-sidebar-default', data: '12.25px' },
      { span: 12, label: '--fontsize-sidebar-selected', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-sidebar-collapse-icon', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-sidebar-hover', data: '12.25px' },
      { span: 12, label: '--fontsize-base', data: '12.25px' },
      { span: 12, label: '--fontsize-component-title-arrow', data: '17.5px' },
      { span: 12, label: '--fontsize-comment-more-button', data: '14px' },
      { span: 12, label: '--fontsize-kanban-header-title', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-kanban-header-count', data: '12.25px' },
      { span: 12, label: '--fontsize-kanban-card-title', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-kanban-card-content', data: '14px' },
      { span: 12, label: '--fontsize-kanban-card-tags', data: '12.25px' },
      { span: 12, label: '--fontsize-list-cell-default', data: '12.25px' },
      { span: 12, label: '--fontsize-list-cell-direct-edit', data: '17.5px' },
      { span: 12, label: '--fontsize-list-cell-rating', data: '17.5px' },
      { span: 12, label: '--fontsize-tab-item', data: '14px' },
      { span: 12, label: '--fontsize-tree-node', data: '14px' },
      { span: 12, label: '--fontsize-tree-button', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-box-label', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-box-data-suffix', data: '21px' },
      { span: 12, label: '--fontsize-box-data-default', data: '49px' },
      { span: 12, label: '--fontsize-fileupload-detail-info', data: '12.25px' },
      { span: 12, label: '--fontsize-fileupload-desc', data: '10.5px' },
      { span: 12, label: '--fontsize-input', data: '12.25px' },
      { span: 12, label: '--fontsize-label', data: '12.25px' },
      { span: 12, label: '--fontsize-inlineedittoolbar-icon', data: '14px' },
      { span: 12, label: '--fontsize-breadcrumb-default', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-breadcrumb-active', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-dropdownmenu-item', data: '12.25px' },
      { span: 12, label: '--fontsize-header-icon', data: '21px' },
      { span: 12, label: '--fontsize-header-dropdownmenu-item', data: '14px' },
      { span: 12, label: '--fontsize-avatar-name', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-tags-item', data: '14px' },
      { span: 12, label: '--fontsize-popup-title', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-popup-close-button', data: '21px' },
      { span: 12, label: '--fontsize-confirm-content', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-confirm-button', data: '16.099999999999998px' },
      { span: 12, label: '--fontsize-button-default', data: '12.25px' },
      { span: 12, label: '--fontsize-form-button', data: '12.25px' },
      { span: 12, label: '--fontsize-step-default', data: '16.099999999999998px' },
      { span: 12, label: '--spacing-gap-s', data: '5px' },
      { span: 12, label: '--spacing-gap-m', data: '7.5px' },
      { span: 12, label: '--spacing-gap-default', data: '7.5px' },
      { span: 12, label: '--spacing-gap-l', data: '10px' },
      { span: 12, label: '--spacing-gap-xl', data: '15px' },
      { span: 12, label: '--spacing-gap-2xl', data: '20px' },
      { span: 12, label: '--spacing-gap-3xl', data: '30px' },
      { span: 12, label: '--spacing-gap-xs', data: '4.5px' },
      { span: 12, label: '--spacing-kanban-padding-top', data: '10px' },
      { span: 12, label: '--spacing-kanban-card-tags-x', data: '6px' },
      { span: 12, label: '--spacing-kanban-card-tags-y', data: '2px' },
      { span: 12, label: '--spacing-kanban-card-tags-margin', data: '15px' },
      { span: 12, label: '--spacing-kanban-card-padding', data: '10px' },
      { span: 12, label: '--spacing-rightpanel-x', data: '20px' },
      { span: 12, label: '--spacing-bottompanel-x', data: '20px' },
      { span: 12, label: '--spacing-sidebar-sidemenu-level', data: '20px' },
      { span: 12, label: '--spacing-list-cell-x', data: '7.5px' },
      { span: 12, label: '--spacing-list-cell-y', data: '6.5px' },
      { span: 12, label: '--spacing-tab-padding-y', data: '10px' },
      { span: 12, label: '--spacing-tab-item-padding-x', data: '20px' },
      { span: 12, label: '--spacing-tab-item-margin-left', data: '15px' },
      { span: 12, label: '--spacing-layout-padding-x', data: '20px' },
      { span: 12, label: '--spacing-component-padding-top', data: '5px' },
      { span: 12, label: '--spacing-component-margin-bottom', data: '15px' },
      { span: 12, label: '--spacing-input-padding-x', data: '7.5px' },
      { span: 12, label: '--spacing-input-padding-y', data: '5px' },
      { span: 12, label: '--spacing-textarea-x', data: '15px' },
      { span: 12, label: '--spacing-textarea-y', data: '5px' },
      { span: 12, label: '--spacing-tree-padding-top', data: '10px' },
      { span: 12, label: '--spacing-header-item-margin-x', data: '20px' },
      { span: 12, label: '--spacing-tags-padding-y', data: '10px' },
      { span: 12, label: '--spacing-tags-item-margin-x', data: '15px' },
      { span: 12, label: '--spacing-tags-item-y', data: '4px' },
      { span: 12, label: '--spacing-tags-item-x', data: '10px' },
      { span: 12, label: '--spacing-comment-item-margin-bottom', data: '10px' },
      { span: 12, label: '--spacing-comment-more-button-padding-y', data: '10px' },
      { span: 12, label: '--spacing-comment-padding', data: '15px' },
      { span: 12, label: '--spacing-timeline-padding-top', data: '10px' },
      { span: 12, label: '--spacing-timeline-item-title-margin-bottom', data: '15px' },
      { span: 12, label: '--spacing-schedule-padding-top', data: '10px' },
      { span: 12, label: '--spacing-form-padding-top', data: '10px' },
      { span: 12, label: '--spacing-form-item-margin-bottom', data: '20px' },
      { span: 12, label: '--spacing-form-item-label-margin-bottom', data: '2px' },
      { span: 12, label: '--opacity-inlineedittoolbar-icon', data: '20%' },
      { span: 12, label: '--opacity-overlay-loading', data: '30%' },
      { span: 12, label: '--sizing-scrollbar', data: '6px' },
    ],
  },
]
</script>

<template>
  <div class="ev-screen horizontal is-full">
    <div class="ev-component" v-for="formDataItem in formData">
      <el-scrollbar class="ev-component-scrollbar">
        <div class="ev-form">
          <h3>{{ formDataItem.tableName }}</h3>
          <el-row v-for="tableDataItem in formDataItem.tableData">
            <!-- <el-col :span="tableDataItem.span"> -->
            <el-col>
              <span class="form-label">{{ tableDataItem.label }}</span>
              <span class="form-data">{{ tableDataItem.data }}</span>
            </el-col>
          </el-row>
        </div>
      </el-scrollbar>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.ev-form {
  h3 {
  }
  .el-row {
    border: 1px solid var(--el-border-color);
    border-bottom: initial;

    &:last-of-type {
      border-bottom: 1px solid var(--el-border-color);
    }

    [class*='el-col-'] {
      display: flex;
      justify-content: space-between;
      padding: 8px;
    }
  }
}
</style>